.TH F2I "1" "" "f2i" "User Commands"
.SH NAME
f2i \- Converts float-point image to the integer one.
.SH SYNOPSIS
.br
.B f2i [OPTIONS...] <input> <output>
.SH DESCRIPTION
.PP
Can also output minimum and maximum values of the image.
./ START OPTION
.RS
.SH ARGUMENTS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<input>\fR
.RS
Input image.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<output>\fR
.RS
Output image.
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH OPTIONS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-m\fR, \fB\-\-min\fR=\fIFLOAT\fR
.RS
Pixel value corresponding to black.
.br
 All values below this will turn black.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-M\fR, \fB\-\-max\fR=\fIFLOAT\fR
.RS
Pixel value corresponding to white.
.br
 All values above this will turn white.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-\-minmax\fR
.RS
Outputs minimum and maximum of the image.
.br
If this option is given no float-to-int conversion is done and no output image is written.
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH Standard options.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-v\fR, \fB\-\-verbose\fR
.RS
Verbose output.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-?\fR, \fB\-\-usage\fR
.RS
Outputs brief usage message.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-h\fR, \fB\-\-help\fR
.RS
Outputs help message.
.br
When combined with the "-v|--verbose" option may output more detailed message.
.RE
./ END OPTION
./
./ START OPTION
.br
.SH SEE ALSO:
.br
ctas(1), ctas-bg(1), ctas-ct(1), ctas-ct-abs(1), ctas-ct-dei(1), ctas-ct-edei(1), ctas-ct-ipc(1), ctas-dei(1), ctas-edei(1), ctas-ipc(1), ctas-f2i(1), ctas-ff(1), ctas-sino(1), ctas-sino-abs(1), ctas-sino-dei(1), ctas-sino-ipc(1), ctas-ts(1), ctas-ct-line(1)
./ END OPTION
./
