.TH DEI "1" "" "dei" "User Commands"
.SH NAME
dei \- DEI contrast processing.
.SH SYNOPSIS
.br
.B dei [OPTIONS...] <minus> <plus>
.SH DESCRIPTION
.PP
Takes two images recorded in different positions of the analyzing crystal and process them with the DEI method separating the apparent absorption and clean refraction components and saving the requested one(s).
./ START OPTION
.RS
.SH ARGUMENTS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<minus>\fR
.RS
Contrast in the minus position.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<plus>\fR
.RS
Contrast in the plus position.
.RE
./ END OPTION
./
./ START OPTION
.RS
<minus>, <plus>. Two images recorded in different position of the analyzing crystal. Must be of equal sizes.
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH OPTIONS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-r\fR, \fB\-\-refraction\fR=\fIPATH\fR
.RS
Image name to output refraction component.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-a\fR, \fB\-\-absorption\fR=\fIPATH\fR
.RS
Image name to output absorption component.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-i\fR, \fB\-\-int\fR
.RS
Output image(s) as integer.
.br
If this option is not set, the output format defaults to the 32-bit float-point TIFF (regardless of the extension). If it is set, the image format is derived from the output file extension (TIFF if the extension does not correspond to any format).
.RE
./ END OPTION
./
./ START OPTION
.RS
.SS DEI input parameters.
.br
Options required for the DEI processing.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-m\fR, \fB\-\-minus-rc\fR=\fIFLOAT\fR
.RS
Reflectivity in the minus position.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-p\fR, \fB\-\-plus-rc\fR=\fIFLOAT\fR
.RS
Reflectivity in the plus position.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-M\fR, \fB\-\-minus-drv\fR=\fIFLOAT\fR
.RS
Derivative of the RC in the minus position.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-P\fR, \fB\-\-plus-drv\fR=\fIFLOAT\fR
.RS
Derivative of the RC in the plus position.
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH Standard options.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-v\fR, \fB\-\-verbose\fR
.RS
Verbose output.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-?\fR, \fB\-\-usage\fR
.RS
Outputs brief usage message.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-h\fR, \fB\-\-help\fR
.RS
Outputs help message.
.br
When combined with the "-v|--verbose" option may output more detailed message.
.RE
./ END OPTION
./
./ START OPTION
.br
.SH SEE ALSO:
.br
ctas(1), ctas-bg(1), ctas-ct(1), ctas-ct-abs(1), ctas-ct-dei(1), ctas-ct-edei(1), ctas-ct-ipc(1), ctas-dei(1), ctas-edei(1), ctas-ipc(1), ctas-f2i(1), ctas-ff(1), ctas-sino(1), ctas-sino-abs(1), ctas-sino-dei(1), ctas-sino-ipc(1), ctas-ts(1), ctas-ct-line(1)
./ END OPTION
./
