.TH FF "1" "" "ff" "User Commands"
.SH NAME
ff \- Flat field correction.
.SH SYNOPSIS
.br
.B ff [OPTIONS...] <foreground> <background> <dark current...>
.SH DESCRIPTION
.PP
For each foreground-background pair of pixels in the corresponding images removes the dark field, divides the foreground by the background and puts the result into the output image. If the background pixel is 0 then the result is 1. All input images must be of equal size.
./ START OPTION
.RS
.SH ARGUMENTS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<foreground>\fR
.RS
Input foreground image.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<background>\fR
.RS
Input background image.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<dark current>\fR
.RS
Input dark current image(s).
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH OPTIONS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIPATH\fR
.RS
Output image.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-w\fR, \fB\-\-idealworld\fR
.RS
Suppose we live in the ideal world.
.br
In the ideal absorption contrast the value of the background always exceeds the respective value of the foreground (i.e. foreground/background <= 1). If this option is used, the points where the ratio exceeds 1, are set to 1.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-i\fR, \fB\-\-int\fR
.RS
Output image(s) as integer.
.br
If this option is not set, the output format defaults to the 32-bit float-point TIFF (regardless of the extension). If it is set, the image format is derived from the output file extension (TIFF if the extension does not correspond to any format).
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH Standard options.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-v\fR, \fB\-\-verbose\fR
.RS
Verbose output.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-?\fR, \fB\-\-usage\fR
.RS
Outputs brief usage message.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-h\fR, \fB\-\-help\fR
.RS
Outputs help message.
.br
When combined with the "-v|--verbose" option may output more detailed message.
.RE
./ END OPTION
./
./ START OPTION
.br
.SH SEE ALSO:
.br
ctas(1), ctas-bg(1), ctas-ct(1), ctas-ct-abs(1), ctas-ct-dei(1), ctas-ct-edei(1), ctas-ct-ipc(1), ctas-dei(1), ctas-edei(1), ctas-ipc(1), ctas-f2i(1), ctas-ff(1), ctas-sino(1), ctas-sino-abs(1), ctas-sino-dei(1), ctas-sino-ipc(1), ctas-ts(1), ctas-ct-line(1)
./ END OPTION
./
