.TH SINO "1" "" "sino" "User Commands"
.SH NAME
sino \- Prepares sinogram from the stack of files.
.SH SYNOPSIS
.br
.B sino [OPTIONS...] <sinogram> <input images...>
.SH DESCRIPTION
.PP
Reads once certain line from all input images in the order they appear in the argument list and forms the sinogram from the lines red. All input images must be of the same size.
./ START OPTION
.RS
.SH ARGUMENTS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<sinogram>\fR
.RS
Output image to store the sinogram.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<input images>\fR
.RS
List of the input images.
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH OPTIONS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-s\fR, \fB\-\-slice\fR=\fIUINT\fR
.RS
Slice index which forms the sinogram.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-i\fR, \fB\-\-int\fR
.RS
Output image(s) as integer.
.br
If this option is not set, the output format defaults to the 32-bit float-point TIFF (regardless of the extension). If it is set, the image format is derived from the output file extension (TIFF if the extension does not correspond to any format).
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH Standard options.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-v\fR, \fB\-\-verbose\fR
.RS
Verbose output.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-?\fR, \fB\-\-usage\fR
.RS
Outputs brief usage message.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-h\fR, \fB\-\-help\fR
.RS
Outputs help message.
.br
When combined with the "-v|--verbose" option may output more detailed message.
.RE
./ END OPTION
./
./ START OPTION
.br
.SH SEE ALSO:
.br
ctas(1), ctas-bg(1), ctas-ct(1), ctas-ct-abs(1), ctas-ct-dei(1), ctas-ct-edei(1), ctas-ct-ipc(1), ctas-dei(1), ctas-edei(1), ctas-ipc(1), ctas-f2i(1), ctas-ff(1), ctas-sino(1), ctas-sino-abs(1), ctas-sino-dei(1), ctas-sino-ipc(1), ctas-ts(1), ctas-ct-line(1)
./ END OPTION
./
