.TH TS "1" "" "ts" "User Commands"
.SH NAME
ts \- Tomosynthesis reconstruction.
.SH SYNOPSIS
.br
.B ts [OPTIONS...] <data file> <result>
.SH DESCRIPTION
.PP
The program reads file which describes the images containing TS projections and performs TS reconstruction of the requested plane.
./ START OPTION
.RS
.SH ARGUMENTS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<data file>\fR
.RS
Input file describing the projection images.
.br
 Must consist only of the strings containing the the following strings:
.br
    <float> <string>
.br
The first component (float value) represents the angle in degree at which the projection was recorded, while the second component gives the file name of the image with the projection. For example:
.br
    -25.5 ../acquire/projection_-25.5.tif
.br
The path to the file is relative to the path of the data file.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<result>\fR
.RS
Output reconstructed image.
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH OPTIONS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-C\fR, \fB\-\-contrast\fR=\fISTRING\fR
.RS
Input component.
.br
Type of the contrast presented in the sinogram. Must be one of the following strings (case insensitive):
.br
A, ABS, ABSORPTION - for the absorption contrast
.br
R, REF, REFRACTION - for the refraction contrast
.br
P, PHS, PHASE      - for the phase contrast
.br
F, FLT, FILTERED   - for the pre-filtered contrast
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-y\fR, \fB\-\-plane\fR=\fIINT\fR
.RS
Plane of the reconstruction.
.br
Relative to the rotation center.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-c\fR, \fB\-\-center\fR=\fIFLOAT\fR
.RS
Rotation center.
.br
Deviation of the rotation axis from the center of the sinogram.
.br
Allows you to erase some minor artifacts in the reconstructed image which come from the inaccurate rotation position. In most real CT or TS experiments the rotation center of the sample is not exactly in the center of the recoded projection. Moreover, the rotation axis may be inclined from the vertical orientation. If the inclination of the rotation axis is noticeable for your desired spatial resolution then you should rotate the images before the actual reconstruction. You can do it in the batch using "mogrify" command from the ImageMagick package with the -rotate option.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-i\fR, \fB\-\-int\fR
.RS
Output image(s) as integer.
.br
If this option is not set, the output format defaults to the 32-bit float-point TIFF (regardless of the extension). If it is set, the image format is derived from the output file extension (TIFF if the extension does not correspond to any format).
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH Standard options.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-v\fR, \fB\-\-verbose\fR
.RS
Verbose output.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-?\fR, \fB\-\-usage\fR
.RS
Outputs brief usage message.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-h\fR, \fB\-\-help\fR
.RS
Outputs help message.
.br
When combined with the "-v|--verbose" option may output more detailed message.
.RE
./ END OPTION
./
./ START OPTION
.br
.SH SEE ALSO:
.br
ctas(1), ctas-bg(1), ctas-ct(1), ctas-ct-abs(1), ctas-ct-dei(1), ctas-ct-edei(1), ctas-ct-ipc(1), ctas-dei(1), ctas-edei(1), ctas-ipc(1), ctas-f2i(1), ctas-ff(1), ctas-sino(1), ctas-sino-abs(1), ctas-sino-dei(1), ctas-sino-ipc(1), ctas-ts(1), ctas-ct-line(1)
./ END OPTION
./
