.TH RC2FD "1" "" "rc2fd" "User Commands"
.SH NAME
rc2fd \- Converts the rocking curve of the analyzer to the function used in the EDEI.
.SH SYNOPSIS
.br
.B rc2fd [OPTIONS...] <FD>
.SH DESCRIPTION
.PP
I use this program only to develop and debug the EDEI algorithm. If you you are not interested in it, you don't need this program.
./ START OPTION
.RS
.SH ARGUMENTS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<FD>\fR
.RS
File containing processed RC used inside the EDEI.
.br
The EDEI algorithm (described in "A. Maksimenko, Nonlinear extension of the x-ray diffraction enhanced imaging, Appl. Phys. Lett. 90, 154106 (2007)") makes use of the function derived from the RC of the analyzer (see function $F^{-1}$ defined in eq.(3)). The file assumes one virtual axis X which represents the value $x=(I_L-I_H)/(I_L-I_H)$ and can be constructed from the number of the line (n) in the file as follows: $x=2*(n-1)/(N-1)-1$, where N is the total number of lines in the file. The file itself must consist only of the strings of the form:
.br
    <alpha> <LH>
.br
where both elements are the floating-point numbers and <alpha> is the $\alpha(x)=F^{-1}(x)$, while <LH> is the combination of the reflectivities on the low- and high-angle side of the RC $I_L+I_H$ in the corresponding $\alpha(x)$ position.
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH OPTIONS:
.RE
./ END OPTION
./
./ START OPTION
.RS
.SS EDEI processing options.
.br
Options which influence the component extraction via the EDEI method.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-m\fR, \fB\-\-minus-point\fR=\fIFLOAT\fR
.RS
Value determining the minus-point.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-p\fR, \fB\-\-plus-point\fR=\fIFLOAT\fR
.RS
Value determining the plus-point.
.RE
./ END OPTION
./
./ START OPTION
.RS
Options "-m, --minus-point" and "-p, --plus-point". The meaning of the value is defined by the -I|--meaning option.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-I\fR, \fB\-\-meaning\fR=\fISTRING\fR
.RS
Meaning of -m, --minus-point and -p, --plus-point options.
.br
Can be one of the following strings (case insensitive):
.br
  "A", "ALPHA" -  Sets the meaning of the +/- values to the angle \alpha. I.e. finds the given value on the \alpha axis of the RC (first column in the input RC file) and sets the position to the found point.
.br
  "N", "NUMBER" - Sets the meaning of the +/- values to the RC index. Converts values to integer and considers them as the index on the RC's \alpha axis. In other words the given values represent the string in the RC file which corresponds to the position.
.br
  "I", "INTENSITY" - Sets the meaning of the +/- values to the intensity. I.e. finds the given value on the intensity axis of the RC (second column in the input RC file) and sets the position to the found point.
.br
  "R", "REFLECTIVITY" - Sets the meaning of the +/- values to the reflectivity. Similar to "INTENSITY", but normalizes the intensities and interprets the values as the normalized ones.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-S\fR, \fB\-\-scale\fR=\fIFLOAT\fR
.RS
Data-to-angle conversion coefficient.
.br
Multiplication of this coefficient by the value in the first column of the rocking curve data file gives the actual angle in radians.
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH Standard options.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-v\fR, \fB\-\-verbose\fR
.RS
Verbose output.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-?\fR, \fB\-\-usage\fR
.RS
Outputs brief usage message.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-h\fR, \fB\-\-help\fR
.RS
Outputs help message.
.br
When combined with the "-v|--verbose" option may output more detailed message.
.RE
./ END OPTION
./
./ START OPTION
.br
.SH SEE ALSO:
.br
ctas(1), ctas-bg(1), ctas-ct(1), ctas-ct-abs(1), ctas-ct-dei(1), ctas-ct-edei(1), ctas-ct-ipc(1), ctas-dei(1), ctas-edei(1), ctas-ipc(1), ctas-f2i(1), ctas-ff(1), ctas-sino(1), ctas-sino-abs(1), ctas-sino-dei(1), ctas-sino-ipc(1), ctas-ts(1), ctas-ct-line(1)
./ END OPTION
./
