.TH CT "1" "" "ct" "User Commands"
.SH NAME
ct \- CT reconstruction of one sinogram.
.SH SYNOPSIS
.br
.B ct [OPTIONS...] <sinogram> <result>
.SH DESCRIPTION
.PP
The program reads pre-formed sinogram and reconstructs it.
./ START OPTION
.RS
.SH ARGUMENTS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<sinogram>\fR
.RS
Input image containing the sinogram.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB<result>\fR
.RS
Output reconstructed image.
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH OPTIONS:
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-C\fR, \fB\-\-contrast\fR=\fISTRING\fR
.RS
Input component.
.br
Type of the contrast presented in the sinogram. Must be one of the following strings (case insensitive):
.br
A, ABS, ABSORPTION - for the absorption contrast
.br
R, REF, REFRACTION - for the refraction contrast
.br
P, PHS, PHASE      - for the phase contrast
.br
F, FLT, FILTERED   - for the pre-filtered contrast
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-c\fR, \fB\-\-center\fR=\fIFLOAT\fR
.RS
Rotation center.
.br
Deviation of the rotation axis from the center of the sinogram.
.br
Allows you to erase some minor artifacts in the reconstructed image which come from the inaccurate rotation position. In most real CT or TS experiments the rotation center of the sample is not exactly in the center of the recoded projection. Moreover, the rotation axis may be inclined from the vertical orientation. If the inclination of the rotation axis is noticeable for your desired spatial resolution then you should rotate the images before the actual reconstruction. You can do it in the batch using "mogrify" command from the ImageMagick package with the -rotate option.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-f\fR, \fB\-\-filter\fR=\fISTRING[:FLOAT]\fR
.RS
Filtering window used in the CT.
.br
Must be a string consisting of two parts (the second one is optional): the filter name and float parameter of the filter. The filter name can be one of the following (case insensitive):
.br
    RAMP
.br
    BARLETT
.br
    WELCH
.br
    PARZEN
.br
    HANN
.br
    HAMMING
.br
    BLACKMAN
.br
    LANCKZOS
.br
    KAISER
.br
    GAUSS
.br
Optional float value is required only if the filter is KAISER or GAUSS and represents the \alpha parameter of the KAISER filter or \sigma parameter of the GAUSS filter. Description of the filtering functions and their graphs can be found in the html documentation.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-r\fR, \fB\-\-resolution\fR=\fIFLOAT\fR
.RS
Pixel size (micron).
.br
Size of the image pixel in microns. If not present, the program attempts to to calculate it from the image dpi.The value is required only to produce the physically correct output. If not set the results are qualitative rather than quantitative.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-t\fR, \fB\-\-threads\fR=\fIUINT\fR
.RS
Number of threads used in calculations.
.br
If the option is not used the optimal number is calculated automatically.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-i\fR, \fB\-\-int\fR
.RS
Output image(s) as integer.
.br
If this option is not set, the output format defaults to the 32-bit float-point TIFF (regardless of the extension). If it is set, the image format is derived from the output file extension (TIFF if the extension does not correspond to any format).
.RE
./ END OPTION
./
./ START OPTION
.RS
.SH Standard options.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-v\fR, \fB\-\-verbose\fR
.RS
Verbose output.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-?\fR, \fB\-\-usage\fR
.RS
Outputs brief usage message.
.RE
./ END OPTION
./
./ START OPTION
.TP
\fB\-h\fR, \fB\-\-help\fR
.RS
Outputs help message.
.br
When combined with the "-v|--verbose" option may output more detailed message.
.RE
./ END OPTION
./
./ START OPTION
.br
.SH SEE ALSO:
.br
ctas(1), ctas-bg(1), ctas-ct(1), ctas-ct-abs(1), ctas-ct-dei(1), ctas-ct-edei(1), ctas-ct-ipc(1), ctas-dei(1), ctas-edei(1), ctas-ipc(1), ctas-f2i(1), ctas-ff(1), ctas-sino(1), ctas-sino-abs(1), ctas-sino-dei(1), ctas-sino-ipc(1), ctas-ts(1), ctas-ct-line(1)
./ END OPTION
./
