SinoS Class Reference
Projections storage.
#include <experiment.h>
Public Member Functions
SinoS (const Experiment &exp, const std::vector< int > &sliceV, bool _verb=false)
Constructor.
~SinoS ()
Destructor.
int pixels () const
Pixels.
int slices () const
Slices.
int thetas () const
Thetas.
void sino (int idx, Map &storage) const
Prepares the sinogram.
Private Member Functions
int index (int idx) const
Checks correctness of the index.
Private Attributes
long pxls
Number of pixels (width) in the projection.
long thts
Number of projections (sinogram height).
long slcs
Number of slices (projection height).
size_t allpix
Number of pixels in the 3D array.
Volume data
3D array.
int mapfile
Map file descriptor (if map memory to file)
bool verb
Show progress bar.
Static Private Attributes
static const std::string modname = `sinogram array`
Module name.
Detailed Description
Projections storage. This class constructs the 3D array of the input data and then can form and output the sinograms.
If you want to build the sinograms from your own type of experiment, Build a class inheriting from the Experiment class. See how it is implemented in the DEIexp, EDEIexp constructors.
Definition at line 215 of file experiment.h.
Constructor & Destructor Documentation
SinoS::SinoS (const Experiment & exp, const std::vector< int > & sliceV, bool _verb = false)
Constructor.
Constructs the 3D array from the absorption contrast projections.
Parameters
exp The experiment.
sliceV List of slices of the interest.
_verb Show progress bar.
Definition at line 620 of file experiment.cpp.
References allpix, data, mapfile, modname, Experiment::pixels(), Experiment::projection(), pxls, slcs, Experiment::slices(), tempfile(), Experiment::thetas(), throw_error(), thts, toString(), ProgressBar::update(), verb, and warn().
SinoS::~SinoS ()
Destructor.
Definition at line 663 of file experiment.cpp.
References allpix, data, and mapfile.
Member Function Documentation
int SinoS::index (int idx) const [private]
Checks correctness of the index.
Checks if the index is within the allowed region.
Parameters
idx The index to check.
Returns
The index.
Definition at line 693 of file experiment.cpp.
References modname, slcs, throw_error(), and toString().
Referenced by sino().
int SinoS::pixels () const
Pixels.
Definition at line 702 of file experiment.cpp.
References pxls.
void SinoS::sino (int idx, Map & storage) const
Prepares the sinogram.
Forms the sinogram.
Parameters
idx Index of the sinogram to form.
storage Storage for the sinogram.
Definition at line 678 of file experiment.cpp.
References data, index(), pxls, and thts.
Referenced by main().
int SinoS::slices () const
Slices.
Definition at line 707 of file experiment.cpp.
References slcs.
int SinoS::thetas () const
Thetas.
Definition at line 712 of file experiment.cpp.
References thts.
Member Data Documentation
size_t SinoS::allpix [private]
Number of pixels in the 3D array.
Definition at line 223 of file experiment.h.
Referenced by SinoS(), and ~SinoS().
Volume SinoS::data [private]
3D array.
Definition at line 224 of file experiment.h.
Referenced by sino(), SinoS(), and ~SinoS().
int SinoS::mapfile [private]
Map file descriptor (if map memory to file)
Definition at line 225 of file experiment.h.
Referenced by SinoS(), and ~SinoS().
const string SinoS::modname = `sinogram array` [static, private]
Module name.
Definition at line 219 of file experiment.h.
Referenced by index(), and SinoS().
long SinoS::pxls [private]
Number of pixels (width) in the projection.
Definition at line 220 of file experiment.h.
Referenced by pixels(), sino(), and SinoS().
long SinoS::slcs [private]
Number of slices (projection height).
Definition at line 222 of file experiment.h.
Referenced by index(), SinoS(), and slices().
long SinoS::thts [private]
Number of projections (sinogram height).
Definition at line 221 of file experiment.h.
Referenced by sino(), SinoS(), and thetas().
bool SinoS::verb [private]
Show progress bar.
Definition at line 226 of file experiment.h.
Referenced by SinoS().
The documentation for this class was generated from the following files:
/home/antonmx/work/projects/ctascmake/src/common/experiment.h
/home/antonmx/work/projects/ctascmake/src/common/experiment.cpp