poptmx::OptionTable Class Reference
The table of known options.
#include <poptmx.h>
Public Member Functions
OptionTable (const std::string &_general_desc=``, const std::string &_general_long_desc=``, const std::string &_general_synopsis=``)
Constructor.
OptionTable & add (const OptionTable &_val)
Incorporates preexisting option table into the table.
OptionTable & add (Kind _kind, void *_val, int(*_convert)(void *, const std::string &), const char _char_name, const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_arg_desc, const std::string &_dflt, bool _is_array)
Abstract interface to add an entry into the table.
OptionTable & add (Kind _kind, void *_val, int(*_convert)(void *, const std::string &), const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_arg_desc, const std::string &_dflt, bool _is_array)
Abstract interface to add the argument into the table.
template<class BClass >
OptionTable & add (Kind _kind, BClass *_val, const char _char_name, const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_dflt=``)
Simplified interface to add the option into the table.
template<class BClass >
OptionTable & add (Kind _kind, std::vector< BClass > *_val, const char _char_name, const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_dflt=``)
Simplified interface to add multiple-appearing option into the table.
template<class BClass >
OptionTable & add (Kind _kind, BClass *_val, const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_dflt=``)
Simplified interface to add the argument into the table.
template<class BClass >
OptionTable & add (Kind _kind, std::vector< BClass > *_val, const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_dflt=``)
Simplified interface to add multiple-appearing argument into the table.
OptionTable & add (Kind _kind, const std::string &_short_desc, const std::string &_long_desc=``)
Adds note or man.
OptionTable & add_verbose (bool *_beverb=0)
Includes standard verbose option.
OptionTable & add_help (bool *_helpme=0)
Includes standard help option.
OptionTable & add_usage (bool *_useme=0)
Includes standard usage option.
OptionTable & add_standard_options (bool *_beverb=0, bool *_helpme=0, bool *_useme=0)
Includes all three standard options;.
bool parse (int argc, char *argv[])
bool has (const void *_val) const
Tells if the entry with the _val exists in the table.
bool has (const std::string &_long_name) const
Tells if the entry with the _long_name exists in the table.
bool has (const char _char_name) const
Tells if the entry with the _char_name exists in the table.
int count (const void *_val=0) const
Returns number of times the entry was processed in parse().
std::string desc (const void *_val) const
Returns the description of the entry with the value.
int size () const
Size of the table.
void usage () const
Constructs the usage message.
void Usage () const
Constructs the verbose usage message.
void help () const
Constructs the help message.
void Help () const
Constructs the verbose help message.
void man () const
Manages man pages.
std::string name () const
Returns the command name as invoked.
void name (const std::string &_name)
Sets the command name.
Public Attributes
std::list< std::string > unused
The array of the CLI words which left unprocessed by the parser.
Private Types
typedef std::list< Option >::iterator ListO
Just to short the text.
Private Member Functions
ListO find (const void *_val) const
Finds entry by value.
ListO find (char _char_name) const
Finds entry by short name.
ListO find (const std::string &_long_name) const
Finds entry by long name.
ListO find () const
Finds first parse-able argument.
ListO has_array () const
True if the table has an array argument.
OptionTable & add (const Option &opt)
Adds the entry in to the table.
void replacePointers (std::string &str)
Replaces all pointer marks.
Private Attributes
std::list< Option > options
The table containing all options, arguments, etc.
std::string general_desc
std::string general_long_desc
std::string general_synopsis
std::string general_name
Program name (as invoked).
bool helpme
To be used for the help, if none is provided.
bool useme
To be used for the usage, if none is provided.
bool beverb
To be used for the verbose, if none is provided.
bool * auto_help
Indicates that autohelp was used.
bool * auto_use
Indicates that autouse was used.
bool * auto_verb
Indicates that autoverb was used.
Static Private Attributes
static const std::string manLN = `-very-long-key-phrase-to-output-man-pages`
The key phrase which triggers the man()
static const std::string pntrMark = `##PNTR##`
Prefixes and suffixes the printed pointer in the text.
Detailed Description
The table of known options. The main (and the only) class to be used by the end user. It stores the information about the program including the general description, all known options and arguments, parses the command line phrase basing on the elements, and may output the usage and/or help messages as well as prepare the manual page for the program.
Within this class the variables ending with `*_long_desc` would be shown in the verbose help message and will go to the manual pages. The variables ending with `*_desc` would be shown in both verbose and non-verbose help messages.
Definition at line 234 of file poptmx.h.
Member Typedef Documentation
typedef std::list<Option>::iterator poptmx::OptionTable::ListO [private]
Just to short the text.
Definition at line 239 of file poptmx.h.
Constructor & Destructor Documentation
poptmx::OptionTable::OptionTable (const std::string & _general_desc = ``, const std::string & _general_long_desc = ``, const std::string & _general_synopsis = ``)
Constructor.
Parameters
_general_desc General description of the table (program description).
_general_long_desc Long description of the table (program).
_general_synopsis Synopsis of the program.
Definition at line 558 of file poptmx.cpp.
Member Function Documentation
OptionTable & poptmx::OptionTable::add (const Option & opt) [private]
Adds the entry in to the table.
General interface to add the entry into the table. All other interfaces should use this one.
Parameters
opt Entry to be added.
Definition at line 925 of file poptmx.cpp.
References poptmx::ARGUMENT, poptmx::Option::char_name, poptmx::Option::desc(), find(), has(), has_array(), poptmx::Option::isarray, poptmx::Option::kind, poptmx::Option::long_name, options, and throw_error().
Referenced by add(), add_help(), add_standard_options(), add_usage(), add_verbose(), clargs::clargs(), EDEIoptions::options(), and DEIoptions::options().
OptionTable & poptmx::OptionTable::add (const OptionTable & _val)
Incorporates preexisting option table into the table.
First puts the general_desc and general_long_desc into the note-entry of the table. Then adds all entries of the _val to the table one-by-one.
Parameters
_val The table to be incorporated.
Definition at line 1035 of file poptmx.cpp.
References add(), general_desc, general_long_desc, poptmx::NOTE, options, and warn().
OptionTable & poptmx::OptionTable::add (Kind _kind, void * _val, int(*)(void *, const std::string &) _convert, const char _char_name, const std::string & _long_name, const std::string & _short_desc, const std::string & _long_desc, const std::string & _arg_desc, const std::string & _dflt, bool _is_array)
Abstract interface to add an entry into the table.
Most abstract and most flexible user interface to add an entry into the table. Should be used only when the user wants to redefine one of the standard type entry.
Parameters
_kind Option::kind
_val Option::val
_convert Option::convert
_char_name Option::char_name
_long_name Option::long_name
_short_desc Option::short_desc
_long_desc Option:: long_desc
_arg_desc Option::arg_desc
_is_array Option::isarray
Definition at line 965 of file poptmx.cpp.
References add().
OptionTable & poptmx::OptionTable::add (Kind _kind, void * _val, int(*)(void *, const std::string &) _convert, const std::string & _long_name, const std::string & _short_desc, const std::string & _long_desc, const std::string & _arg_desc, const std::string & _dflt, bool _is_array)
Abstract interface to add the argument into the table.
Most abstract and most flexible user interface to add an argument into the table. Should be used only when the user wants to redefine one of the standard type entry.
Parameters
_kind Option::kind
_val Option::val
_convert Option::convert
_long_name Option::long_name
_short_desc Option::short_desc
_long_desc Option:: long_desc
_arg_desc Option::arg_desc
_is_array Option::isarray
Definition at line 988 of file poptmx.cpp.
References add(), poptmx::ARGUMENT, and throw_error().
OptionTable & poptmx::OptionTable::add (Kind _kind, const std::string & _short_desc, const std::string & _long_desc = ``)
Adds note or man.
Adds new note or manual page string to the entry table. If adding the note just copies the *_desc into the appropriate elements of the entry. If adding man-page then behaviour is more complex: If the long description is empty then adds the short description would appear in the man file as is, without any changes. Otherwise will add the short description as the section header and long description as the section's text.
Parameters
_kind Kind of entry to add. In this context can be ::NOTE or ::MAN
_short_desc Note which would appear in the help messages and manual page
_long_desc Note which would appear in the verbose help message and manual page
Definition at line 1014 of file poptmx.cpp.
References add(), poptmx::MAN, poptmx::NOTE, and throw_error().
OptionTable & poptmx::OptionTable::add_help (bool * _helpme = 0)
Includes standard help option.
Parameters
_helpme The variable to be updated by the option-trigger if 0-pointer, then uses internal one (OptionTable::helpme);
Definition at line 1072 of file poptmx.cpp.
References add(), auto_help, helpme, and poptmx::OPTION.
Referenced by add_standard_options().
OptionTable & poptmx::OptionTable::add_standard_options (bool * _beverb = 0, bool * _helpme = 0, bool * _useme = 0)
Includes all three standard options;.
Parameters
_beverb The variable to be updated by the option-trigger if 0-pointer, then uses internal one (OptionTable::beverb);
_useme The variable to be updated by the option-trigger if 0-pointer, then uses internal one (OptionTable::useme);
_helpme The variable to be updated by the option-trigger if 0-pointer, then uses internal one (OptionTable::helpme);
Definition at line 1088 of file poptmx.cpp.
References add(), add_help(), add_usage(), add_verbose(), auto_help, auto_verb, find(), and poptmx::NOTE.
OptionTable & poptmx::OptionTable::add_usage (bool * _useme = 0)
Includes standard usage option.
Parameters
_useme The variable to be updated by the option-trigger if 0-pointer, then uses internal one (OptionTable::useme);
Definition at line 1061 of file poptmx.cpp.
References add(), auto_use, poptmx::OPTION, and useme.
Referenced by add_standard_options().
OptionTable & poptmx::OptionTable::add_verbose (bool * _beverb = 0)
Includes standard verbose option.
Parameters
_beverb The variable to be updated by the option-trigger if 0-pointer, then uses internal one (OptionTable::beverb);
Definition at line 1050 of file poptmx.cpp.
References add(), auto_verb, beverb, and poptmx::OPTION.
Referenced by add_standard_options().
int poptmx::OptionTable::count (const void * _val = 0) const
Returns number of times the entry was processed in parse().
Parameters
_val The value to check.
Returns
If _val is non-zero - number of the times the entry was triggered from the CLI phrase. If _val is zero - number of times all entries were triggered.
Definition at line 1144 of file poptmx.cpp.
References find(), has(), options, and throw_error().
Referenced by clargs::clargs().
string poptmx::OptionTable::desc (const void * _val) const
Returns the description of the entry with the value.
If the entry does not exist in the table and the pointer is non-zero, the returned string is the pointer mark which later, after the entry was added to the table, can be replaced using the ::replacePointers(string &).
Parameters
_val The value to check
Returns
Description.
Definition at line 1167 of file poptmx.cpp.
References find(), has(), pntrMark, and throw_error().
Referenced by EDEIoptions::options(), and replacePointers().
OptionTable::ListO poptmx::OptionTable::find () const [private]
Finds first parse-able argument.
Finds the first of the argument entries in the table which can take one more value: i.e. either an argument which was not met before, or the argument which accept multiple entries.
Returns
The pointer to the table entry or 0-pointer if no entry is found.
Definition at line 637 of file poptmx.cpp.
References poptmx::ARGUMENT, and options.
Referenced by add(), add_standard_options(), count(), desc(), has(), parse(), Usage(), and usage().
OptionTable::ListO poptmx::OptionTable::find (char _char_name) const [private]
Finds entry by short name.
Finds the entry in the options with the Option.char_name equal to _char_name.
Parameters
_char_name The value to search for.
Returns
The pointer to the table entry or 0-pointer if no entry is found.
Definition at line 603 of file poptmx.cpp.
References poptmx::ARGUMENT, poptmx::OPTION, and options.
OptionTable::ListO poptmx::OptionTable::find (const std::string & _long_name) const [private]
Finds entry by long name.
Finds the entry in the options with the Option.long_name equal to _long_name.
Parameters
_long_name The value to search for.
Returns
The pointer to the table entry or 0-pointer if no entry is found.
Definition at line 620 of file poptmx.cpp.
References poptmx::ARGUMENT, poptmx::OPTION, and options.
OptionTable::ListO poptmx::OptionTable::find (const void * _val) const [private]
Finds entry by value.
Finds the entry in the options with the Option.val equal to _val.
Parameters
_val The value to search for.
Returns
The pointer to the table entry or 0-pointer if no entry is found.
Definition at line 589 of file poptmx.cpp.
References options.
bool poptmx::OptionTable::has (const char _char_name) const
Tells if the entry with the _char_name exists in the table.
Tells if the entry with the _val exists in the table.
Parameters
_char_name - entry value to search for.
Returns
true if found, false otherwise.
Definition at line 1132 of file poptmx.cpp.
References find(), and options.
bool poptmx::OptionTable::has (const void * _val) const
Tells if the entry with the _val exists in the table.
Tells if the entry with the _val exists in the table.
Parameters
_val - entry value to search for.
Returns
true if found, false otherwise.
Definition at line 1108 of file poptmx.cpp.
References find(), and options.
Referenced by add(), count(), desc(), and replacePointers().
bool poptmx::OptionTable::has (const std::string & _long_name) const
Tells if the entry with the _long_name exists in the table.
Tells if the entry with the _val exists in the table.
Parameters
_long_name - long name to search for.
Returns
true if found, false otherwise.
Definition at line 1120 of file poptmx.cpp.
References find(), and options.
OptionTable::ListO poptmx::OptionTable::has_array () const [private]
True if the table has an array argument.
Finds the first of the argument entries in the table which can take one more value: i.e. either an argument which was not met before, or the argument which accept multiple entries.
Returns
The pointer to the table entry or 0-pointer if no entry is found.
Definition at line 652 of file poptmx.cpp.
References poptmx::ARGUMENT, and options.
Referenced by add().
void poptmx::OptionTable::Help () const
Constructs the verbose help message.
Definition at line 854 of file poptmx.cpp.
References general_desc, general_long_desc, general_synopsis, and options.
Referenced by parse().
void poptmx::OptionTable::help () const
Constructs the help message.
Definition at line 833 of file poptmx.cpp.
References general_desc, general_synopsis, and options.
Referenced by parse().
void poptmx::OptionTable::man () const
Manages man pages.
Definition at line 871 of file poptmx.cpp.
References general_long_desc, general_synopsis, name(), options, and upper().
Referenced by parse().
void poptmx::OptionTable::name (const std::string & _name)
Sets the command name.
May be useful when you need just to print usage/verbose message before parsing the CLI phrase.
Parameters
_name New command name (usually set to argv[0]).
Definition at line 1228 of file poptmx.cpp.
References general_name.
string poptmx::OptionTable::name () const
Returns the command name as invoked.
Definition at line 1208 of file poptmx.cpp.
References general_name.
Referenced by clargs::clargs(), man(), parse(), and usage().
bool poptmx::OptionTable::parse (int argc, char * argv[])
Parses the whole CLI phrase.
Parameters
argc Number of the arguments in the argv.
argv Pointer to the array of the arguments. The last element must always be 0-pointer.
Returns
false if help or usage man message were printed, true otherwise.
Definition at line 664 of file poptmx.cpp.
References poptmx::ARGUMENT, auto_help, auto_use, auto_verb, find(), general_desc, general_long_desc, general_name, general_synopsis, help(), Help(), man(), manLN, name(), options, replacePointers(), throw_error(), unused, usage(), Usage(), and warn().
Referenced by clargs::clargs().
void poptmx::OptionTable::replacePointers (std::string & str) [private]
Replaces all pointer marks.
Scans the string for the pointer marks, reads the pointer and replaces the mark with the description given by ::desc(const void*).
Parameters
str string to be changed.
Definition at line 1187 of file poptmx.cpp.
References desc(), has(), pntrMark, and throw_error().
Referenced by parse().
int poptmx::OptionTable::size () const
Size of the table.
Definition at line 578 of file poptmx.cpp.
References options.
void poptmx::OptionTable::usage () const
Constructs the usage message.
Definition at line 785 of file poptmx.cpp.
References auto_help, auto_verb, find(), general_desc, name(), and options.
Referenced by clargs::clargs(), and parse().
void poptmx::OptionTable::Usage () const
Constructs the verbose usage message.
Definition at line 808 of file poptmx.cpp.
References auto_help, auto_use, auto_verb, find(), general_desc, general_long_desc, general_synopsis, and options.
Referenced by parse().
Member Data Documentation
bool* poptmx::OptionTable::auto_help [private]
Indicates that autohelp was used.
Definition at line 262 of file poptmx.h.
Referenced by add_help(), add_standard_options(), parse(), Usage(), and usage().
bool* poptmx::OptionTable::auto_use [private]
Indicates that autouse was used.
Definition at line 263 of file poptmx.h.
Referenced by add_usage(), parse(), and Usage().
bool* poptmx::OptionTable::auto_verb [private]
Indicates that autoverb was used.
Definition at line 264 of file poptmx.h.
Referenced by add_standard_options(), add_verbose(), parse(), Usage(), and usage().
bool poptmx::OptionTable::beverb [private]
To be used for the verbose, if none is provided.
Definition at line 261 of file poptmx.h.
Referenced by add_verbose().
std::string poptmx::OptionTable::general_desc [private]
Short description of the program. If the table is included into another option table, this description becomes the short_desc of the note preceeding the included elements.
Definition at line 244 of file poptmx.h.
Referenced by add(), Help(), help(), parse(), Usage(), and usage().
std::string poptmx::OptionTable::general_long_desc [private]
Long description of the program. If the table is included into another option table, this description becomes the long_desc of the note preceeding the included elements.
Definition at line 249 of file poptmx.h.
Referenced by add(), Help(), man(), parse(), and Usage().
std::string poptmx::OptionTable::general_name [private]
Program name (as invoked).
Definition at line 257 of file poptmx.h.
Referenced by name(), and parse().
std::string poptmx::OptionTable::general_synopsis [private]
The string with the synopsis of the program: to be found in the manual page and help messages. If not set then it is automatically generated from the table of options.
Definition at line 254 of file poptmx.h.
Referenced by Help(), help(), man(), parse(), and Usage().
bool poptmx::OptionTable::helpme [private]
To be used for the help, if none is provided.
Definition at line 259 of file poptmx.h.
Referenced by add_help().
const string poptmx::OptionTable::manLN = `-very-long-key-phrase-to-output-man-pages` [static, private]
The key phrase which triggers the man()
Definition at line 275 of file poptmx.h.
Referenced by parse().
std::list<Option> poptmx::OptionTable::options [mutable, private]
The table containing all options, arguments, etc.
Definition at line 238 of file poptmx.h.
Referenced by add(), count(), find(), has(), has_array(), Help(), help(), man(), parse(), size(), Usage(), and usage().
const string poptmx::OptionTable::pntrMark = `##PNTR##` [static, private]
Prefixes and suffixes the printed pointer in the text.
Definition at line 277 of file poptmx.h.
Referenced by desc(), and replacePointers().
std::list<std::string> poptmx::OptionTable::unused
The array of the CLI words which left unprocessed by the parser.
Definition at line 364 of file poptmx.h.
Referenced by parse().
bool poptmx::OptionTable::useme [private]
To be used for the usage, if none is provided.
Definition at line 260 of file poptmx.h.
Referenced by add_usage().
The documentation for this class was generated from the following files:
/home/antonmx/work/projects/ctascmake/src/common/poptmx.h
/home/antonmx/work/projects/ctascmake/src/common/poptmx.cpp