AqSeries Class Reference
Parsing file of the acquisition series.
#include <experiment.h>
Public Member Functions
AqSeries (const Path &filename)
Constructs from file.
Shape shape () const
Shape of the projection image.
long thetas () const
Total number of projections.
long pixels () const
Width of the image.
long slices () const
Number of slices (hight) in the image.
long size () const
Total size of the data.
const Path fg (int idx) const
Gives name of the foreground.
const Path bg (int idx) const
Gives name of the background.
const std::vector< Path > & dc () const
Gives the array of DC images.
void projection (int idx, Map &proj, const std::vector< int > &sliceV=std::vector< int >()) const
Constructs one cleaned projection of the experimental data.
Static Public Attributes
static const std::string Desc = `Empty strings can be used for grouping and have no influence.`
Description of the file with the AqSeries.
Private Types
typedef std::pair< Path, int > fgelement
Private Member Functions
bool isbgstring (const std::string &str) const
Tells if the string represents bgnd.
bool isdcstring (const std::string &str) const
Tells if the string represents dc.
bool iscomment (const std::string &str) const
Tells if the string is a comment.
Path bgname (const std::string &str) const
Extracts filename from the bgdn string.
Path dcname (const std::string &str) const
Extracts filename from the dc string.
int index (int idx) const
Checks correctness of the index.
void darkCurrent (Map &dcc, const std::vector< int > &sliceV) const
Constructs the dark current array.
Private Attributes
std::vector< fgelement > fgs
Storage of foregrounds.
std::vector< Path > bgs
Storage of backgrounds.
std::vector< Path > dcs
Dark current images.
Shape sh
Shape of the input images.
Static Private Attributes
static const std::string modname = `acquisition series`
Module name.
static const int nobg = -1
`Magick number` for the `no background`.
static const std::string BGPREFIX = `#BACKGROUND# `
Background prefix.
static const std::string DCPREFIX = `#DARKCURRENT# `
Dark current prefix.
Detailed Description
Parsing file of the acquisition series. This class parses and stores the list of foreground-background pairs (read ::Desc for more details).
Definition at line 101 of file experiment.h.
Member Typedef Documentation
typedef std::pair< Path, int > AqSeries::fgelement [private]
Element of the foregrounds array: the foreground itself and the index of the corresponding background.
Definition at line 113 of file experiment.h.
Constructor & Destructor Documentation
AqSeries::AqSeries (const Path & filename)
Constructs from file.
Parses input file.
Parses input file as it is described in AqSeries and constructs the foreground and background arrays.
Parameters
filename File with the foreground-background pairs.
Definition at line 47 of file experiment.cpp.
References cdpath(), Path::dir(), ImageSizes(), and throw_error().
Member Function Documentation
const Path AqSeries::bg (int idx) const
Gives name of the background.
Background name.
Parameters
idx Projection index.
Returns
The name of the (image) file containing the background corresponding to the projection index.
Definition at line 192 of file experiment.cpp.
Path AqSeries::bgname (const std::string & str) const [private]
Extracts filename from the bgdn string.
extracts the background name from the background string.
Parameters
str The string to extract from.
Returns
The background filename.
Definition at line 142 of file experiment.cpp.
void AqSeries::darkCurrent (Map & dcc, const std::vector< int > & sliceV) const [private]
Constructs the dark current array.
Constructs the dark current map from all dark-current images in the input file and puts it into the ::dcc array.
Parameters
dcc resulting array.
sliceV
Definition at line 205 of file experiment.cpp.
References ReadImageLine().
const std::vector<Path>& AqSeries::dc () const [inline]
Gives the array of DC images.
Definition at line 144 of file experiment.h.
Path AqSeries::dcname (const std::string & str) const [private]
Extracts filename from the dc string.
extracts the dark current name from the dc string.
Parameters
str The string to extract from.
Returns
The dark current filename.
Definition at line 153 of file experiment.cpp.
const Path AqSeries::fg (int idx) const
Gives name of the foreground.
Foreground name.
Parameters
idx Projection index.
Returns
The name of the (image) file containing the foreground.
Definition at line 179 of file experiment.cpp.
int AqSeries::index (int idx) const [private]
Checks correctness of the index.
Checks if the index is within the allowed region.
Parameters
idx The index to check.
Returns
The index.
Definition at line 165 of file experiment.cpp.
References throw_error(), and toString().
bool AqSeries::isbgstring (const std::string & str) const [private]
Tells if the string represents bgnd.
Tells if the string describes the background.
Parameters
str The string to check
Returns
true if the string describes the background, false otherwise.
Definition at line 108 of file experiment.cpp.
bool AqSeries::iscomment (const std::string & str) const [private]
Tells if the string is a comment.
Parameters
str The string to check
Returns
true if the string is a comment or empty, false otherwise.
Definition at line 130 of file experiment.cpp.
bool AqSeries::isdcstring (const std::string & str) const [private]
Tells if the string represents dc.
Tells if the string describes the dark current.
Parameters
str The string to check
Returns
true if the string describes the dark current, false otherwise.
Definition at line 119 of file experiment.cpp.
long AqSeries::pixels () const [inline]
Width of the image.
Definition at line 137 of file experiment.h.
void AqSeries::projection (int idx, Map & proj, const std::vector< int > & sliceV = std::vector<int>()) const
Constructs one cleaned projection of the experimental data.
Constructs the flat-field subtracted projection from the experimental data at given rotation position ::itheta and puts it into ::proj array.
Parameters
idx rotation position.
proj the array to put data into.
sliceV array of slices to be extracted.
Definition at line 228 of file experiment.cpp.
References flatfield(), ReadImageLine(), throw_error(), and toString().
Referenced by IPCexp::projection(), EDEIexp::projection(), DEIexp::projection(), and ABSexp::projection().
Shape AqSeries::shape () const [inline]
Shape of the projection image.
Definition at line 135 of file experiment.h.
Referenced by IPCexp::IPCexp(), and main().
long AqSeries::size () const [inline]
Total size of the data.
Definition at line 139 of file experiment.h.
Referenced by IPCexp::IPCexp(), and IPCexp::projection().
long AqSeries::slices () const [inline]
Number of slices (hight) in the image.
Definition at line 138 of file experiment.h.
long AqSeries::thetas () const [inline]
Total number of projections.
Definition at line 136 of file experiment.h.
Referenced by IPCexp::IPCexp().
Member Data Documentation
const std::string AqSeries::BGPREFIX = `#BACKGROUND# ` [static, private]
Background prefix.
Definition at line 108 of file experiment.h.
std::vector<Path> AqSeries::bgs [private]
Storage of backgrounds.
Definition at line 116 of file experiment.h.
const std::string AqSeries::DCPREFIX = `#DARKCURRENT# ` [static, private]
Dark current prefix.
Definition at line 109 of file experiment.h.
std::vector<Path> AqSeries::dcs [private]
Dark current images.
Definition at line 117 of file experiment.h.
const std::string AqSeries::Desc = `Empty strings can be used for grouping and have no influence.` [static]
Description of the file with the AqSeries.
Definition at line 150 of file experiment.h.
Referenced by clargs::clargs().
std::vector<fgelement> AqSeries::fgs [private]
Storage of foregrounds.
Definition at line 115 of file experiment.h.
const std::string AqSeries::modname = `acquisition series` [static, private]
Module name.
Definition at line 105 of file experiment.h.
const int AqSeries::nobg = -1 [static, private]
`Magick number` for the `no background`.
Definition at line 106 of file experiment.h.
Shape AqSeries::sh [private]
Shape of the input images.
Definition at line 126 of file experiment.h.
The documentation for this class was generated from the following files:
/home/antonmx/work/projects/ctascmake/src/common/experiment.h
/home/antonmx/work/projects/ctascmake/src/common/experiment.cpp