Contrast Class Reference
Type of the input contrast.
#include <common.h>
Public Types
enum Cntype {
ABS,
REF,
PHS,
FLT
 }
Known contrast types.
Public Member Functions
Contrast (Cntype _cn=FLT)
Constructor from contrast type.
Contrast (const std::string &_name)
Constructor from name.
Cntype contrast () const
Contrast type.
std::string name () const
Name of the contrast type.
Static Public Attributes
static const std::string Desc = `F, FLT, FILTERED - for the pre-filtered contrast`
Description of the option giving the contrast type.
Private Attributes
Cntype _contrast
Type of the contrast.
Static Private Attributes
static const std::string modname = `contrast`
Module name.
Detailed Description
Type of the input contrast. Affects the behaviour of the reconstruction algorithm. See the CTRec class for more details.
When you need to include your own type of contrast follow these steps:
Add your contrast to the Contrast::Cntype enumeration.
Add your contrast to the Contrast::Contrast(const std::string &) constructor
Add your contrast to the Contrast::name() method.
Update the ContrastOptionDesc string as appropriate.
Definition at line 244 of file common.h.
Member Enumeration Documentation
enum Contrast::Cntype
Known contrast types.
Enumerator:
ABS
 Absorption.
REF
 Refraction.
PHS
 Phase.
FLT
 Pre-filtered: ready for backprojection, no filtering needed.
Definition at line 248 of file common.h.
Constructor & Destructor Documentation
Contrast::Contrast (Cntype _cn = FLT)
Constructor from contrast type.
Constructor.
Parameters
_cn Contrast type.
Definition at line 280 of file common.cpp.
Contrast::Contrast (const std::string & _name)
Constructor from name.
Parameters
_name Contrast name.
Definition at line 286 of file common.cpp.
References _contrast, ABS, FLT, name(), PHS, REF, throw_error(), and upper().
Member Function Documentation
Contrast::Cntype Contrast::contrast () const
Contrast type.
Type of contrast.
Returns
Type of contrast
Definition at line 301 of file common.cpp.
References _contrast.
Referenced by CTrec::choose_algorithm(), operator!=(), and operator==().
string Contrast::name () const
Name of the contrast type.
Name of the contrast.
Returns
Name of the contrast.
Definition at line 311 of file common.cpp.
References _contrast, ABS, FLT, PHS, REF, and throw_bug().
Referenced by CTrec::choose_algorithm(), and Contrast().
Member Data Documentation
Cntype Contrast::_contrast [private]
Type of the contrast.
Definition at line 257 of file common.h.
Referenced by contrast(), Contrast(), and name().
const std::string Contrast::Desc = `F, FLT, FILTERED - for the pre-filtered contrast` [static]
Description of the option giving the contrast type.
Definition at line 267 of file common.h.
const string Contrast::modname = `contrast` [static, private]
Module name.
Definition at line 256 of file common.h.
The documentation for this class was generated from the following files:
/home/antonmx/work/projects/ctascmake/src/common/common.h
/home/antonmx/work/projects/ctascmake/src/common/common.cpp