IPCexp Class Reference
Class which extracts IPC-processed projections from the input data.
#include <ipc.h>
Public Member Functions
IPCexp (const AqSeries &_listD, const AqSeries &_list0, const IPCprocess &_proc, IPCprocess::Component _comp)
void projection (int itheta, Map &proj, const std::vector< int > &sliceV=std::vector< int >()) const
Constructs processed projection.
void component (IPCprocess::Component _comp)
void gamma (float _dgamma)
Private Attributes
AqSeries list0
Data acquired in the contact print plane.
AqSeries listD
Data acquired at the distance.
const IPCprocess & proc
IPC processing.
IPCprocess::Component comp
Component to be extracted by the ::projection.
float dd
Pixel size.
float dist
Object-to-detector distance.
float dgamma
$\gamma$ parameter of the BAC
Map pr0
Some internal array used for the extraction.
Map prD
Some internal array used for the extraction.
Static Private Attributes
static const std::string modname = `IPC experiment`
Name of the module.
Detailed Description
Class which extracts IPC-processed projections from the input data. #ifdef _H_EXPERIMENT_H_
Definition at line 206 of file ipc.h.
Constructor & Destructor Documentation
IPCexp::IPCexp (const AqSeries & _listD, const AqSeries & _list0, const IPCprocess & _proc, IPCprocess::Component _comp) [inline]
Contructor.
Parameters
_listD Data acquired at the distance.
_list0 Data acquired in the contact print plane. Can be left empty.
_proc The IPC processor.
_comp Component to be extracted.
Definition at line 232 of file ipc.h.
References component(), list0, modname, proc, Experiment::sh, IPCprocess::shape(), AqSeries::shape(), AqSeries::size(), AqSeries::thetas(), throw_error(), and Experiment::thts.
Member Function Documentation
void IPCexp::component (IPCprocess::Component _comp) [inline]
Sets the component to be extracted and the corresponding contrast type.
Parameters
_comp Component to be extracted.
Definition at line 282 of file ipc.h.
Referenced by IPCexp().
void IPCexp::gamma (float _dgamma) [inline]
Sets the $\gamma$.
Parameters
_dgamma $\gamma$ parameter of the BAC method (theoretically must be 1.0).
Definition at line 291 of file ipc.h.
void IPCexp::projection (int itheta, Map & proj, const std::vector< int > & sliceV = std::vector< int >()) const [inline, virtual]
Constructs processed projection.
Parameters
itheta the number of the projection to be returned.
proj Array to put the projection into.
sliceV array of slices to be extracted.
Implements Experiment.
Definition at line 255 of file ipc.h.
References dgamma, IPCprocess::extract(), list0, listD, pr0, prD, proc, AqSeries::projection(), Experiment::sh, AqSeries::size(), and unzero().
Member Data Documentation
IPCprocess::Component IPCexp::comp [private]
Component to be extracted by the ::projection.
Definition at line 213 of file ipc.h.
float IPCexp::dd [private]
Pixel size.
Definition at line 215 of file ipc.h.
float IPCexp::dgamma [private]
$\gamma$ parameter of the BAC
Definition at line 217 of file ipc.h.
Referenced by projection().
float IPCexp::dist [private]
Object-to-detector distance.
Definition at line 216 of file ipc.h.
AqSeries IPCexp::list0 [private]
Data acquired in the contact print plane.
Definition at line 210 of file ipc.h.
Referenced by IPCexp(), and projection().
AqSeries IPCexp::listD [private]
Data acquired at the distance.
Definition at line 211 of file ipc.h.
Referenced by projection().
Map IPCexp::pr0 [mutable, private]
Some internal array used for the extraction.
Definition at line 219 of file ipc.h.
Referenced by projection().
Map IPCexp::prD [mutable, private]
Some internal array used for the extraction.
Definition at line 220 of file ipc.h.
Referenced by projection().
const IPCprocess& IPCexp::proc [private]
IPC processing.
Definition at line 212 of file ipc.h.
Referenced by IPCexp(), and projection().
The documentation for this class was generated from the following file:
/home/antonmx/work/projects/ctascmake/src/common/ipc.h