Path Class Reference
Path in the directory structure.
#include <common.h>
Inherits std::string.
Public Member Functions
Path (const std::string &str=std::string())
Constructor from string.
Path (const char *str)
Constructor from C-string.
std::string drive () const
Extracts drive letter (has sense on MS WIN only).
std::string dir () const
Extracts directory.
std::string title () const
Extracts title (filename without the extension).
std::string dtitle () const
Extracts title with the preceding full path.
std::string extension () const
Extracts the extension.
std::string name () const
Extracts file name.
bool isdir () const
Tells if the path definitely represents the a directory.
bool isabsolute () const
Tells if the path is absolute.
Path & bedir ()
Makes the path to be the directory (adds DIRSEPARATOR).
Private Member Functions
void throw_unextracted (const std::string &element) const
throws error in extracting an element.
Static Private Attributes
static const std::string DIRSEPARATOR = `/`
Directory separator.
Detailed Description
Path in the directory structure. This class just a wrapper around std::string. It has some additional useful functions which have sense only if the string represents a path. Also a lot of platform specific code is hidden here.
Definition at line 153 of file common.h.
Constructor & Destructor Documentation
Path::Path (const std::string & str = std::string()) [inline]
Constructor from string.
Parameters
str the initializing string.
Definition at line 165 of file common.h.
Path::Path (const char * str) [inline]
Constructor from C-string.
Parameters
str the initializing string.
Definition at line 169 of file common.h.
Member Function Documentation
Path & Path::bedir ()
Makes the path to be the directory (adds DIRSEPARATOR).
Definition at line 214 of file common.cpp.
Referenced by cdpath().
string Path::dir () const
Extracts directory.
Definition at line 140 of file common.cpp.
Referenced by AqSeries::AqSeries(), and upgrade().
string Path::drive () const
Extracts drive letter (has sense on MS WIN only).
Definition at line 128 of file common.cpp.
string Path::dtitle () const
Extracts title with the preceding full path.
Definition at line 183 of file common.cpp.
Referenced by clargs::clargs().
string Path::extension () const
Extracts the extension.
Definition at line 189 of file common.cpp.
Referenced by clargs::clargs().
bool Path::isabsolute () const
Tells if the path is absolute.
Definition at line 222 of file common.cpp.
Referenced by cdpath().
bool Path::isdir () const
Tells if the path definitely represents the a directory.
Definition at line 209 of file common.cpp.
string Path::name () const
Extracts file name.
Definition at line 153 of file common.cpp.
Referenced by upgrade().
void Path::throw_unextracted (const std::string & element) const [private]
throws error in extracting an element.
Constructs the error which reports the unextractable element.
Parameters
element The element whose extraction has failed.
Definition at line 121 of file common.cpp.
References throw_error().
string Path::title () const
Extracts title (filename without the extension).
Definition at line 167 of file common.cpp.
Member Data Documentation
const string Path::DIRSEPARATOR = `/` [static, private]
Directory separator.
Definition at line 157 of file common.h.
The documentation for this class was generated from the following files:
/home/antonmx/work/projects/ctascmake/src/common/common.h
/home/antonmx/work/projects/ctascmake/src/common/common.cpp