Filter Class Reference
Filtering window function.
#include <kernel.h>
Public Types
enum Ftype {
NONE = 0,
RAMP,
BARLETT,
WELCH,
PARZEN,
HANN,
HAMMING,
BLACKMAN,
LANCKZOS,
KAISER,
GAUSS
 }
Filter types.
Public Member Functions
Filter (Ftype _tp=RAMP, float _as=0)
Trivial constructor.
Filter (const std::string &_name, float _as=0)
Constructor from name.
Ftype filter () const
Filter.
std::string name () const
Returns name.
Line & fill (Line &filt, int pixels=0) const
Fills the window.
Private Attributes
Ftype filttp
Filter type.
float alsig
Additional parameter required by some filters.
Static Private Attributes
static const std::string modname = `filter`
Module name.
Detailed Description
Filtering window function. This class holds information about filtering window function and can prepare the filtering window.
Known filters: Filter::Ftype
If you want to add a new filter:
Add your filter into the Filter::Ftype enumeration.
Add your filter to the Filter::Filter(const std::string &, float) constructor
Add your filter to the Filter::name() function.
Add your filter to the Filter::fill() function: additional `case` in the switch-case construction
Add your filter to the Filter::includeFilterTable() option table
If your new filter requires additional parameter(s) then you can add them using the Filter::alsig as the example.
Definition at line 79 of file kernel.h.
Member Enumeration Documentation
enum Filter::Ftype
Filter types.
Enumerator:
NONE
 No filter: 1.
RAMP
 Ramp: $ |k| $.
BARLETT
 Barlett: $ |k|(1-|k|) $.
WELCH
 Welch: $ |k|(1-k^2) $.
PARZEN
 Parzen:
 |k|\times\left\{ \begin{array}{lll} 1-6k^2+3|k|^3 & : & |k|\leq1/2 \cr 2(1+|k|^3) & : & 1/2<|k|\leq1 \end{array} \right. 
HANN
 Hann: $ |k|0.5(1+\cos{\pi k}) $.
HAMMING
 Hamming: $ |k|(0.54+0.46\cos{\pi k}) $.
BLACKMAN
 Blackman: $ |k|(0.42+0.5\cos{\pi k}+0.08\cos{2\pi k}) $.
LANCKZOS
 Lanckzos:
 |k|\frac{\sin{\pi k}}{k} 
.
KAISER
 Kaiser:
 |k|\frac{I_0(\alpha\sqrt{1-k^2})}{I_0(\alpha)} 
.
GAUSS
 Gauss:
 |k|2^{-(k/\sigma)^2} 
.
Definition at line 84 of file kernel.h.
Constructor & Destructor Documentation
Filter::Filter (Ftype _tp = RAMP, float _as = 0)
Trivial constructor.
Constructor.
Parameters
_tp Filter type.
_as Additional parameter.
Definition at line 91 of file kernel.cpp.
Filter::Filter (const std::string & _name, float _as = 0)
Constructor from name.
Constructor.
Similar to the previous one, but reads the filter type from the string.
Parameters
_name Filter name.
_as Additional parameter.
Definition at line 103 of file kernel.cpp.
References BLACKMAN, filttp, GAUSS, HAMMING, HANN, KAISER, LANCKZOS, modname, name(), NONE, PARZEN, RAMP, throw_error(), upper(), and WELCH.
Member Function Documentation
Line & Filter::fill (Line & filt, int pixels = 0) const
Fills the window.
Prepares the window function.
Fills the line with the filter function. If pixels is 0 then reads the the width of the window from the line length.Otherwise resizes the line.
Parameters
filt Line to store the window.
pixels Desired size of the window.
Returns
Filled window.
Definition at line 168 of file kernel.cpp.
References alsig, BARLETT, BLACKMAN, filttp, GAUSS, HAMMING, HANN, KAISER, LANCKZOS, modname, NONE, PARZEN, RAMP, throw_error(), and WELCH.
Referenced by CTrec::filter(), and ts_add().
Filter::Ftype Filter::filter () const
Filter.
Filter type.
Returns
Type of the filter.
Definition at line 151 of file kernel.cpp.
References filttp.
Referenced by operator!=(), and operator==().
string Filter::name () const
Returns name.
Name of the filter type.
Returns
Name of the filter.
Definition at line 127 of file kernel.cpp.
References BARLETT, BLACKMAN, filttp, GAUSS, HAMMING, HANN, KAISER, LANCKZOS, NONE, PARZEN, RAMP, throw_bug(), and WELCH.
Referenced by clargs::clargs(), and Filter().
Member Data Documentation
float Filter::alsig [private]
Additional parameter required by some filters.
Definition at line 130 of file kernel.h.
Referenced by fill().
Ftype Filter::filttp [private]
Filter type.
Definition at line 129 of file kernel.h.
Referenced by fill(), filter(), Filter(), and name().
const string Filter::modname = `filter` [static, private]
Module name.
Definition at line 128 of file kernel.h.
Referenced by fill(), and Filter().
The documentation for this class was generated from the following files:
/home/antonmx/work/projects/ctascmake/src/common/kernel.h
/home/antonmx/work/projects/ctascmake/src/common/kernel.cpp