ProgressBar Class Reference
CLI progress bar (PB).
#include <common.h>
Public Member Functions
ProgressBar (bool _showme=false, const std::string &_message=``, int _steps=0)
Initializing constructor.
void update (int curstep=0)
Updates the progress bar.
void done ()
Finalizes the progress bar.
Private Member Functions
int getwidth ()
Returns current terminal width.
Private Attributes
bool showme
Tells if the bar should be shown.
std::string message
Description of the process.
int steps
Total number of steps in the progress.
int step
Current step.
int waswidth
The width of the terminal in the previous step.
int reservedChs
Symbols for the constant part of the PB.
std::string fmt
Format string used to print the numbers.
Detailed Description
CLI progress bar (PB). This class is used to visualize a progress.
Definition at line 458 of file common.h.
Constructor & Destructor Documentation
ProgressBar::ProgressBar (bool _showme = false, const std::string & _message = ``, int _steps = 0)
Initializing constructor.
Parameters
_showme Tells if the progress bar should be shown.
_message The description of the progress.
_steps Number of steps in the progress. If 0 then unknown.
Definition at line 439 of file common.cpp.
Member Function Documentation
void ProgressBar::done ()
Finalizes the progress bar.
Definition at line 498 of file common.cpp.
References fmt, getwidth(), message, reservedChs, showme, step, steps, toString(), and waswidth.
Referenced by main(), and update().
int ProgressBar::getwidth () [private]
Returns current terminal width.
Definition at line 527 of file common.cpp.
Referenced by done(), and update().
void ProgressBar::update (int curstep = 0)
Updates the progress bar.
Parameters
curstep Current step. Advances +1 if zero.
Definition at line 467 of file common.cpp.
References done(), fmt, getwidth(), reservedChs, showme, step, steps, toString(), and waswidth.
Referenced by main(), and SinoS::SinoS().
Member Data Documentation
std::string ProgressBar::fmt [private]
Format string used to print the numbers.
Definition at line 467 of file common.h.
Referenced by done(), and update().
std::string ProgressBar::message [private]
Description of the process.
Definition at line 462 of file common.h.
Referenced by done().
int ProgressBar::reservedChs [private]
Symbols for the constant part of the PB.
Definition at line 466 of file common.h.
Referenced by done(), and update().
bool ProgressBar::showme [private]
Tells if the bar should be shown.
Definition at line 461 of file common.h.
Referenced by done(), and update().
int ProgressBar::step [private]
Current step.
Definition at line 464 of file common.h.
Referenced by done(), and update().
int ProgressBar::steps [private]
Total number of steps in the progress.
Definition at line 463 of file common.h.
Referenced by done(), and update().
int ProgressBar::waswidth [private]
The width of the terminal in the previous step.
Definition at line 465 of file common.h.
Referenced by done(), and update().
The documentation for this class was generated from the following files:
/home/antonmx/work/projects/ctascmake/src/common/common.h
/home/antonmx/work/projects/ctascmake/src/common/common.cpp