Experiment Class Reference
Parent abstract class for various experimental techniques.
#include <experiment.h>
Public Member Functions
Experiment (const Shape &_sh, long _thetas)
virtual void projection (int itheta, Map &proj, const std::vector< int > &sliceV=std::vector< int >()) const =0
Constructs processed projection.
long thetas () const
Total number of projections.
long pixels () const
Width of the image.
long slices () const
Number of slices (hight) in the image.
Contrast contrast () const
The contrast type of the projection.
Protected Attributes
long thts
Number of projections (sinogram height).
Shape sh
Shape of the projections.
Contrast cntr
The contrast type.
Detailed Description
Parent abstract class for various experimental techniques. When you need to create a new type of experiment, just inherit from this class with implementation of the constructor and projection function. See DEIexp, EDEIexp and ABSexp as the examples.
Definition at line 167 of file experiment.h.
Constructor & Destructor Documentation
Experiment::Experiment (const Shape & _sh, long _thetas) [inline]
Constructor
Parameters
_sh Size of the projection.
_thetas Number of projections.
Definition at line 178 of file experiment.h.
References sh, throw_error(), and thts.
Member Function Documentation
Contrast Experiment::contrast () const [inline]
The contrast type of the projection.
Definition at line 200 of file experiment.h.
References cntr.
Referenced by main().
long Experiment::pixels () const [inline]
Width of the image.
Definition at line 198 of file experiment.h.
References sh.
Referenced by main(), and SinoS::SinoS().
virtual void Experiment::projection (int itheta, Map & proj, const std::vector< int > & sliceV = std::vector< int >()) const [pure virtual]
Constructs processed projection.
Parameters
itheta the number of the projection to be returned.
proj Array to put the projection into.
sliceV array of slices to be extracted.
Implemented in ABSexp, DEIexp, EDEIexp, and IPCexp.
Referenced by SinoS::SinoS().
long Experiment::slices () const [inline]
Number of slices (hight) in the image.
Definition at line 199 of file experiment.h.
References sh.
Referenced by main(), and SinoS::SinoS().
long Experiment::thetas () const [inline]
Total number of projections.
Definition at line 197 of file experiment.h.
References thts.
Referenced by main(), and SinoS::SinoS().
Member Data Documentation
Contrast Experiment::cntr [protected]
The contrast type.
Definition at line 171 of file experiment.h.
Referenced by contrast().
Shape Experiment::sh [protected]
Shape of the projections.
Definition at line 170 of file experiment.h.
Referenced by Experiment(), IPCexp::IPCexp(), pixels(), IPCexp::projection(), EDEIexp::projection(), DEIexp::projection(), and slices().
long Experiment::thts [protected]
Number of projections (sinogram height).
Definition at line 169 of file experiment.h.
Referenced by Experiment(), IPCexp::IPCexp(), and thetas().
The documentation for this class was generated from the following file:
/home/antonmx/work/projects/ctascmake/src/common/experiment.h