CtasErr Class Reference
Error type.
#include <common.h>
Public Types
enum ErrTp {
WARN,
ERR,
FATAL
 }
Error severity.
Public Member Functions
CtasErr (ErrTp _terr, const std::string &mod, const std::string &msg)
Constructor.
ErrTp type () const
Returns error type.
void report () const
Reports the error to the ctderr.
Private Attributes
std::string message
The message which describes the error.
std::string module
Name of the module where the error happened.
ErrTp terr
Error severity.
Detailed Description
Error type.
Definition at line 73 of file common.h.
Member Enumeration Documentation
enum CtasErr::ErrTp
Error severity.
Enumerator:
WARN
 Warning.
ERR
 Error.
FATAL
 Fatal error.
Definition at line 76 of file common.h.
Constructor & Destructor Documentation
CtasErr::CtasErr (ErrTp _terr, const std::string & mod, const std::string & msg) [inline]
Constructor.
Parameters
_terr Sets CtasErr::terr
mod Sets CtasErr::module
msg Sets CtasErr::message
Definition at line 50 of file common.cpp.
Member Function Documentation
void CtasErr::report () const [inline]
Reports the error to the ctderr.
Prints the error into the standard error stream.
Definition at line 58 of file common.cpp.
Referenced by exit_on_error(), throw_error(), and warn().
CtasErr::ErrTp CtasErr::type () const [inline]
Returns error type.
Definition at line 75 of file common.cpp.
Referenced by ReadImage(), and ReadImageLine().
Member Data Documentation
std::string CtasErr::message [private]
The message which describes the error.
Definition at line 83 of file common.h.
std::string CtasErr::module [private]
Name of the module where the error happened.
Definition at line 84 of file common.h.
ErrTp CtasErr::terr [private]
Error severity.
Definition at line 85 of file common.h.
The documentation for this class was generated from the following files:
/home/antonmx/work/projects/ctascmake/src/common/common.h
/home/antonmx/work/projects/ctascmake/src/common/common.cpp