/home/antonmx/work/projects/ctascmake/src/common/common.cpp File Reference
Definitions of function declared in common.h.
#include <algorithm>
#include <stdarg.h>
#include <string.h>
#include `common.h`
#include <termios.h>
#include <sys/ioctl.h>
#include <Magick++.h>
#include <FreeImage.h>
#include <climits>
#include <tiffio.h>
#include <fcntl.h>
Classes
struct ToUpper
Functions
void throw_error (const string &mod, const string &msg)
Constructs the error, reports and then throws it.
void throw_bug (const string &mod)
Reports and throws the bug.
CtasErr warn (const string &mod, const string &msg)
Constructs the warning and reports it.
void exit_on_error (const string &mod, const string &msg)
Constructs the error, reports and then exits.
Path upgrade (const Path &path, const string &addthis)
Upgrades the filename with an addition.
Path cdpath (const Path &dir, const Path &file)
Adds the path to the filename.
string type_desc (Path *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool _conversion (Path *_val, const string &in)
Converts the string `in` into the Path _val. To be used in the CLI parsing via `poptmx` library.
bool operator== (const Contrast &a, const Contrast &b)
Compare contrasts.
bool operator!= (const Contrast &a, const Contrast &b)
Compare contrasts.
string type_desc (Contrast *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool _conversion (Contrast *_val, const string &in)
Converts the string `in` into the Contrast _val. To be used in the CLI parsing via `poptmx` library.
string upper (string str)
Convert string to upper case.
string lower (string str)
Convert string to lower case.
string toString (const string fmt,...)
Prints formatted message to string.
static void initMagick ()
initializes ImageMagick library
static FIBITMAP * FImageLoader (const Path &filename)
float PixelSize (const Path &filename)
Pixel size of the image.
Shape ImageSizes (const Path &filename)
Image sizes.
void ImageSizes (const Path &filename, int *width, int *hight)
Image sizes.
void BadShape (const Path &filename, const Shape &shp)
Check the shape of the image.
template<class StClass >
static void fip2arr (Map &storage, FIBITMAP *dib)
static void ReadImage_FI (const Path &filename, Map &storage)
static void ReadImage_IM (const Path &filename, Map &storage)
void ReadImage (const Path &filename, Map &storage)
Load image from preopened object.
void ReadImage (const Path &filename, Map &storage, const Shape &shp)
Load image checking the shape.
template<class StClass >
static void fip2ln (Line &storage, FIBITMAP *dib, int idx)
static void ReadImageLine_FI (const Path &filename, Line &storage, int idx)
Reads one line of the image using FreeImage library.
static void ReadImageLine_IM (const Path &filename, Line &storage, int idx)
Reads one line of the image using ImageMagick library.
void ReadImageLine (const Path &filename, Line &storage, int idx)
Load one line of the image.
void ReadImageLine (const Path &filename, Line &storage, int idx, const Shape &shp)
Load one line of the image.
static void ReadImageLine_FI (const Path &filename, Map &storage, const vector< int > &idxs)
Reads many lines of the image using FreeImage library.
static void ReadImageLine_IM (const Path &filename, Map &storage, const vector< int > &idxs)
Reads many line of the image using ImageMagick library.
void ReadImageLine (const Path &filename, Map &storage, const vector< int > &idxs)
Load several lines of the image.
void ReadImageLine (const Path &filename, Map &storage, const vector< int > &idxs, const Shape &shp)
Load several lines of the image.
static void SaveImageINT_FI (const Path &filename, const Map &storage)
static void SaveImageINT_IM (const Path &filename, const Map &storage)
float blitz::limit01 (float x)
static void SaveImageINT (const Path &filename, const Map &storage, float minval=0, float maxval=0)
Save the array into integer image.
void SaveImageFP (const Path &filename, const Map &storage)
Save the array into float point TIFF image.
void SaveImage (const Path &filename, const Map &storage, bool saveint)
Save the array into image.
void SaveImage (const Path &filename, const Map &storage, float minval, float maxval)
Save the array into integer image.
void SaveData (const Path filename,...)
Save any amount of lines into data file.
void LoadData (const Path filename,...)
Loads any amount of lines from data file.
Variables
const std::string IntOptionDesc = ` to any format).`
Description of the -i, --int option used in many modules.
const std::string NeedForQuant = ` If not set the results are qualitative rather than quantitative.`
The note added to many options.
const std::string ResolutionOptionDesc = ` to calculate it from the image dpi.` + NeedForQuant
Description of the --resolution option used in many modules.
const std::string SeeAlsoList = ` ctas-ts(1), ctas-ct-line(1)`
static bool CtasMagickInited = false
true if ImageMagick has been initialized.
Detailed Description
Definitions of function declared in common.h.
Author
antonmx <antonmx@synchrotron.org.au>
Date
Thu Jul 17 12:51:00 2008
Here the functions declared in common.h are defined.
Definition in file common.cpp.
Function Documentation
static FIBITMAP* FImageLoader (const Path & filename) [static]
Loads the FreeImage image.
For further use with FreeImage library's functions. Do not forget to unload image afterwards.
Parameters
filename Name of the image.
Returns
Definition at line 600 of file common.cpp.
References warn().
Referenced by ReadImage_FI(), and ReadImageLine_FI().
template<class StClass > static void fip2arr (Map & storage, FIBITMAP * dib) [inline, static]
Reads FreeImage image into the array.
Parameters
storage The array to read into.
dib Image to read.
Definition at line 694 of file common.cpp.
template<class StClass > static void fip2ln (Line & storage, FIBITMAP * dib, int idx) [inline, static]
Reads one line of the FreeImage image.
Parameters
storage The array to store the line
dib The image to read from.
idx The index of the line to read.
Definition at line 819 of file common.cpp.
static void initMagick () [inline, static]
initializes ImageMagick library
Use it in all binaries to allow reading up to 10k x 10k into memory, not HDD.
Definition at line 566 of file common.cpp.
References CtasMagickInited.
Referenced by ReadImage_IM(), ReadImageLine_IM(), and SaveImageINT_IM().
static void ReadImage_FI (const Path & filename, Map & storage) [static]
Loads an image using FreeImage library.
Parameters
filename Name of the image
storage The array to store the image.
Definition at line 720 of file common.cpp.
References FImageLoader(), and warn().
Referenced by ReadImage().
static void ReadImage_IM (const Path & filename, Map & storage) [static]
Loads an image using ImageMagick library.
Parameters
filename Name of the image
storage The array to store the image.
Definition at line 759 of file common.cpp.
References initMagick(), throw_error(), and warn().
Referenced by ReadImage().
static void ReadImageLine_FI (const Path & filename, Map & storage, const vector< int > & idxs) [static]
Reads many lines of the image using FreeImage library.
Parameters
filename The name of the file with the image.
storage Array to read into.
idxs The indexes of the line to read.
Definition at line 952 of file common.cpp.
References FImageLoader(), toString(), and warn().
static void ReadImageLine_FI (const Path & filename, Line & storage, int idx) [static]
Reads one line of the image using FreeImage library.
Parameters
filename The name of the file with the image.
storage Line to read into.
idx The index of the line to read.
Definition at line 846 of file common.cpp.
References FImageLoader(), throw_error(), toString(), and warn().
Referenced by ReadImageLine().
static void ReadImageLine_IM (const Path & filename, Line & storage, int idx) [static]
Reads one line of the image using ImageMagick library.
Parameters
filename The name of the file with the image.
storage Line to read into.
idx The index of the line to read.
Definition at line 897 of file common.cpp.
References initMagick(), throw_error(), toString(), and warn().
Referenced by ReadImageLine().
static void ReadImageLine_IM (const Path & filename, Map & storage, const vector< int > & idxs) [static]
Reads many line of the image using ImageMagick library.
Parameters
filename The name of the file with the image.
storage Array to read into.
idxs The indexes of the line to read.
Definition at line 1007 of file common.cpp.
References initMagick(), toString(), and warn().
void SaveImageFP (const Path & filename, const Map & storage)
Save the array into float point TIFF image.
Stores the array in the float-point TIFF file. Be careful: limited number of editors/viewers/analyzers support float point format.
Parameters
filename the name of the image file image.
storage the array to be written to the image.
Definition at line 1235 of file common.cpp.
Referenced by SaveImage().
static void SaveImageINT (const Path & filename, const Map & storage, float minval = 0, float maxval = 0) [static]
Save the array into integer image.
Stores the array in the integer-based image. If minval is equal to maxval then the minimum and maximum values of the array data corresponds to black and white respectively.
Parameters
filename the name of the image file image.
storage the array to be written to the image.
minval the value corresponding to black.
maxval the value corresponding to white.
Definition at line 1186 of file common.cpp.
Referenced by SaveImage().
static void SaveImageINT_FI (const Path & filename, const Map & storage) [static]
Saves image in integer format using FreeImage library.
Parameters
filename file to save image into.
storage array with the image.
Definition at line 1078 of file common.cpp.
References warn().
static void SaveImageINT_IM (const Path & filename, const Map & storage) [static]
Saves image in integer format using ImageMagick library.
Parameters
filename file to save image into.
storage array with the image.
Definition at line 1120 of file common.cpp.
References initMagick(), and throw_error().
Variable Documentation
bool CtasMagickInited = false [static]
true if ImageMagick has been initialized.
Definition at line 560 of file common.cpp.
Referenced by initMagick().