/home/antonmx/work/projects/ctascmake/src/executables/ct-abs.cpp File Reference
All-in-one ct reconstruction of the absorption contrast.
#include <vector>
#include `../common/common.h`
#include `../common/kernel.h`
#include `../common/experiment.h`
#include `../common/abs.h`
#include `../common/poptmx.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'ctabs'.
Detailed Description
All-in-one ct reconstruction of the absorption contrast.
Author
antonmx <antonmx@gmail.com>
Date
Mon Jul 21 10:09:31 2008
Main file for the program which reads the input sinogram from image, performs CT reconstruction of it and stores the result in other image file
Definition in file ct-abs.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'ctabs'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 134 of file ct-abs.cpp.
References clargs::beverbose, clargs::center, Experiment::contrast(), clargs::filter_type, clargs::idealworld, clargs::listname, mask2format(), clargs::nof_threads, clargs::outmask, Experiment::pixels(), SaveImage(), clargs::SaveInt, SinoS::sino(), slice_str2vec(), clargs::slicedesc, Experiment::slices(), Experiment::thetas(), and toString().