/home/antonmx/work/projects/ctascmake/src/executables/ct-dei.cpp File Reference
All-in-one ct reconstruction of the refraction contrast.
#include <vector>
#include `../common/common.h`
#include `../common/kernel.h`
#include `../common/experiment.h`
#include `../common/dei.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'ctref'.
Detailed Description
All-in-one ct reconstruction of the refraction contrast.
Author
antonmx <antonmx@gmail.com>
Date
Mon Jul 21 10:09:31 2008
Definition in file ct-dei.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'ctref'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 227 of file ct-dei.cpp.
References clargs::beverbose, clargs::center, Experiment::contrast(), clargs::contrast, clargs::deiopt, clargs::filter_type, DEIoptions::Gm, DEIoptions::Gp, mask2format(), clargs::Mlistname, clargs::nof_threads, clargs::outmask, Experiment::pixels(), clargs::Plistname, DEIoptions::Rm, DEIoptions::Rp, SaveImage(), clargs::SaveInt, SinoS::sino(), slice_str2vec(), clargs::slicedesc, Experiment::slices(), Experiment::thetas(), and toString().