/home/antonmx/work/projects/ctascmake/src/executables/ct-edei.cpp File Reference
All-in-one ct reconstruction of the refraction contrast.
#include <vector>
#include `../common/common.h`
#include `../common/kernel.h`
#include `../common/experiment.h`
#include `../common/edei.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'ctref'.
Detailed Description
All-in-one ct reconstruction of the refraction contrast.
Author
antonmx <antonmx@gmail.com>
Date
Mon Jul 21 10:09:31 2008
Main file for the program which reads the input sinogram from image, performs CT reconstruction of it and stores the result in other image file.
Definition in file ct-edei.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'ctref'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 232 of file ct-edei.cpp.
References EDEIoptions::acof, clargs::beverbose, clargs::center, Experiment::contrast(), clargs::contrast, clargs::edeiopt, clargs::filter_type, EDEIoptions::Gm, EDEIoptions::Gp, mask2format(), clargs::Mlistname, EDEIoptions::mpinter, clargs::nof_threads, clargs::outmask, Experiment::pixels(), clargs::Plistname, EDEIoptions::RCname, SaveImage(), clargs::SaveInt, SinoS::sino(), slice_str2vec(), clargs::slicedesc, Experiment::slices(), EDEIoptions::smooth, Experiment::thetas(), and toString().