/home/antonmx/work/projects/ctascmake/src/executables/ct-ipc.cpp File Reference
All-in-one ct reconstruction of the inline phase contrast.
#include <vector>
#include `../common/common.h`
#include `../common/experiment.h`
#include `../common/ipc.h`
#include `../common/poptmx.h`
#include `../common/kernel.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'sinr'.
Detailed Description
All-in-one ct reconstruction of the inline phase contrast.
Author
antonmx <antonmx@gmail.com>
Date
Wed Jul 7 13:18:49 2010
Definition in file ct-ipc.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'sinr'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 183 of file ct-ipc.cpp.
References clargs::alpha, clargs::beverbose, clargs::center, clargs::contrast, clargs::dd, clargs::dgamma, clargs::dist, clargs::filter_type, CTrec::finilize(), clargs::lambda, mask2format(), clargs::nof_threads, clargs::outmask, SaveImage(), clargs::SaveInt, AqSeries::shape(), SinoS::sino(), slice_str2vec(), clargs::slicedesc, toString(), clargs::z0_list, and clargs::zD_list.