/home/antonmx/work/projects/ctascmake/src/executables/ct-line.cpp File Reference
Reconstruction of one slice on the reconstruct-as-acquired approach.
#include `../common/common.h`
#include `../common/kernel.h`
#include `../common/poptmx.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
static int getLine (Line &sinoline, float &Theta)
int main (int argc, char *argv[])
Main function for 'ct'.
Variables
int imageSlice
Slice number to pick up in the projections.
Detailed Description
Reconstruction of one slice on the reconstruct-as-acquired approach.
Author
antonmx <antonmx@gmail.com>
Date
Mon Jul 21 10:09:31 2008
Main file for the program which reconstructs one slice from the set of images as they are ready to read.
Definition in file ct-line.cpp.
Function Documentation
static int getLine (Line & sinoline, float & Theta) [static]
Parses the input string.
Reads the projection angle and the name of the image file from the stdin, then puts the line from the projection read from image into the ::sinoline and the angle of the projection into ::Theta.
Parameters
sinoline line storage
Theta projection angle
Returns
0 if this is the end of input, non-zero otherwise
Definition at line 132 of file ct-line.cpp.
References ImageSizes(), imageSlice, ReadImageLine(), throw_error(), and toString().
Referenced by main().
int main (int argc, char * argv[])
Main function for 'ct'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 164 of file ct-line.cpp.
References CTrec::addLine(), clargs::beverbose, clargs::center, clargs::contrast, ProgressBar::done(), clargs::filter_type, getLine(), imageSlice, clargs::result_name, SaveImage(), clargs::SaveInt, clargs::slice, throw_error(), and ProgressBar::update().
Variable Documentation
int imageSlice
Slice number to pick up in the projections.
Definition at line 115 of file ct-line.cpp.
Referenced by getLine(), and main().