/home/antonmx/work/projects/ctascmake/src/executables/ct.cpp File Reference
Reconstruction of one sinogram.
#include `../common/common.h`
#include `../common/kernel.h`
#include `../common/poptmx.h`
#include `FreeImage.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'ct'.
Detailed Description
Reconstruction of one sinogram.
Author
antonmx <antonmx@gmail.com>
Date
Mon Jul 21 10:09:31 2008
Main file for the program which reads the input sinogram from image, performs CT reconstruction of it and stores the result in other image file
Definition in file ct.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'ct'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 129 of file ct.cpp.
References clargs::center, clargs::contrast, clargs::dd, clargs::filter_type, CTrec::finilize(), clargs::nof_threads, ReadImage(), CTrec::reconstruct(), clargs::result_name, SaveImage(), clargs::SaveInt, and clargs::sinogram_name.