/home/antonmx/work/projects/ctascmake/src/executables/dei.cpp File Reference
Extracts refraction and/or absorption components of two contrasts taken on the either sides of the analyzers RC. Uses DEI or EDEI methods.
#include `../common/common.h`
#include `../common/dei.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'dei'.
Detailed Description
Extracts refraction and/or absorption components of two contrasts taken on the either sides of the analyzers RC. Uses DEI or EDEI methods.
Author
antonmx <antonmx@synchrotron.org.au>
Date
Thu Sep 11 18:55:53 2008
Definition in file dei.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'dei'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 115 of file dei.cpp.
References DEIprocess::ABS, clargs::abs_name, clargs::command, clargs::deiopt, exit_on_error(), DEIprocess::extract(), DEIoptions::Gm, DEIoptions::Gp, clargs::minus_name, clargs::plus_name, ReadImage(), DEIprocess::REF, clargs::ref_name, DEIoptions::Rm, DEIoptions::Rp, SaveImage(), and clargs::SaveInt.