/home/antonmx/work/projects/ctascmake/src/executables/edei.cpp File Reference
Extracts refraction and/or absorption components of two contrasts taken on the either sides of the analyzers RC. Uses DEI or EDEI methods.
#include `../common/common.h`
#include `../common/edei.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'dei'.
Detailed Description
Extracts refraction and/or absorption components of two contrasts taken on the either sides of the analyzers RC. Uses DEI or EDEI methods.
Author
antonmx <antonmx@synchrotron.org.au>
Date
Thu Sep 11 18:55:53 2008
Definition in file edei.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'dei'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 117 of file edei.cpp.
References EDEIprocess::ABS, clargs::abs_name, EDEIoptions::acof, clargs::command, clargs::edeiopt, exit_on_error(), EDEIprocess::extract(), EDEIoptions::Gm, EDEIoptions::Gp, clargs::minus_name, EDEIoptions::mpinter, clargs::plus_name, EDEIoptions::RCname, ReadImage(), EDEIprocess::REF, clargs::ref_name, SaveImage(), clargs::SaveInt, and EDEIoptions::smooth.