/home/antonmx/work/projects/ctascmake/src/common/experiment.cpp File Reference
Definitions of the functions declared in experiment.h.
#include `experiment.h`
#include `flatfield.h`
#include `poptmx.h`
#include <algorithm>
#include <sys/mman.h>
#include <string.h>
Functions
string mask2format (const string &mask, int maxslice)
Converts the mask string to the format string.
static vector< int > & rmadd (vector< int > &arr, int numb, bool negate)
Adds or removes the element into the array.
static int str2n (const string &str)
Parses the string to non-negative integer.
vector< int > slice_str2vec (const string &sliceS, int hight)
Constructs the array of slices.
static int tempfile (const off_t size)
Prepares the temporary file to map the memory to.
string type_desc (Dcenter *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool _conversion (Dcenter *_val, const string &in)
Converts the string `in` into the Dcenter _val. To be used in the CLI parsing via `poptmx` library.
Variables
const string MaskDesc = ` any directory.`
Description of the output result mask.
const string SliceOptionDesc = ` 440 to 449, 471 to 500, 800 to 909, 915 and 921 to the end.`
Description of the option giving the string of slices.
const string DcenterOptionDesc = ` from the ImageMagick package with the -rotate option.`
Description of the option giving the Dcenter type.
Detailed Description
Definitions of the functions declared in experiment.h.
Author
antonmx <antonmx@gmail.com>
Date
Mon Jul 21 10:09:31 2008
Definition in file experiment.cpp.
Function Documentation
static vector<int>& rmadd (vector< int > & arr, int numb, bool negate) [inline, static]
Adds or removes the element into the array.
Adds or removes the element numb to/from the array depending on negation.
Parameters
arr The array to be updated.
numb The element to be added/removed to/from the array.
negate If true then removes, if false then adds to the array.
Returns
Updated array.
Definition at line 370 of file experiment.cpp.
Referenced by slice_str2vec().
static int str2n (const string & str) [inline, static]
Parses the string to non-negative integer.
Parameters
str The string to parse.
Returns
The result of parsing.
Definition at line 384 of file experiment.cpp.
References warn().
Referenced by slice_str2vec().
static int tempfile (const off_t size) [inline, static]
Prepares the temporary file to map the memory to.
Parameters
size Size of the memory region to be mapped.
Returns
The file descriptor
Definition at line 573 of file experiment.cpp.
References throw_error(), toString(), and warn().
Referenced by SinoS::SinoS().