/home/antonmx/work/projects/ctascmake/src/executables/ff.cpp File Reference
Remove the background.
#include `../common/common.h`
#include `../common/flatfield.h`
#include `../common/poptmx.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'ff'.
Detailed Description
Remove the background.
Author
antonmx <antonmx@asw062.synchrotron.org.au>
Date
Thu Jul 24 13:55:58 2008
Takes `foreground` and `background` image files as input, divides one by other and writes the result to the `output` image.
Definition in file ff.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'ff'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 112 of file ff.cpp.
References clargs::background_name, clargs::command, clargs::dc_names, exit_on_error(), flatfield(), clargs::foreground_name, clargs::idealworld, clargs::output_name, ReadImage(), SaveImage(), and clargs::SaveInt.