CLI parsing.
Classes
class poptmx::Err
Error type.
class poptmx::Option
Single entry in the option table. Represents all types of entries.
class poptmx::OptionTable
The table of known options.
Enumerations
enum poptmx::Kind {
poptmx::OPTION,
poptmx::ARGUMENT,
poptmx::NOTE,
poptmx::MAN,
poptmx::PROC
 }
Type of the element in the table of the known options.
Functions
static void poptmx::throw_error (const std::string &mod, const std::string &msg)
Constructs the error, reports and then throws it.
static Err poptmx::warn (const std::string &mod, const std::string &msg)
Constructs the warning and reports it.
template<class BClass >
int poptmx::conversion (void *_val, const std::string &in)
template<class BClass >
int poptmx::arr_conversion (void *_val, const std::string &in)
template<class BClass >
OptionTable & poptmx::OptionTable::add (Kind _kind, BClass *_val, const char _char_name, const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_dflt=``)
Simplified interface to add the option into the table.
template<class BClass >
OptionTable & poptmx::OptionTable::add (Kind _kind, BClass *_val, const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_dflt=``)
Simplified interface to add the argument into the table.
template<class BClass >
OptionTable & poptmx::OptionTable::add (Kind _kind, std::vector< BClass > *_val, const char _char_name, const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_dflt=``)
Simplified interface to add multiple-appearing option into the table.
template<class BClass >
OptionTable & poptmx::OptionTable::add (Kind _kind, std::vector< BClass > *_val, const std::string &_long_name, const std::string &_short_desc, const std::string &_long_desc, const std::string &_dflt=``)
Simplified interface to add multiple-appearing argument into the table.
int poptmx::_conversion (bool *_val, const string &)
string poptmx::type_desc (bool *)
int poptmx::_conversion (string *_val, const string &in)
string poptmx::type_desc (string *)
int poptmx::_conversion (char *_val, const string &in)
string poptmx::type_desc (char *)
int poptmx::_conversion (unsigned char *_val, const string &in)
string poptmx::type_desc (unsigned char *)
int poptmx::_conversion (short *_val, const string &in)
string poptmx::type_desc (short *)
int poptmx::_conversion (unsigned short *_val, const string &in)
string poptmx::type_desc (unsigned short *)
int poptmx::_conversion (int *_val, const string &in)
string poptmx::type_desc (int *)
int poptmx::_conversion (unsigned int *_val, const string &in)
string poptmx::type_desc (unsigned int *)
int poptmx::_conversion (long *_val, const string &in)
string poptmx::type_desc (long *)
int poptmx::_conversion (unsigned long *_val, const string &in)
string poptmx::type_desc (unsigned long *)
int poptmx::_conversion (long long *_val, const string &in)
string poptmx::type_desc (long long *)
int poptmx::_conversion (unsigned long long *_val, const string &in)
string poptmx::type_desc (unsigned long long *)
int poptmx::_conversion (float *_val, const string &in)
string poptmx::type_desc (float *)
int poptmx::_conversion (double *_val, const string &in)
string poptmx::type_desc (double *)
template<class BClass >
static int poptmx::_int_conversion (BClass *_val, const string &in)
template<class BClass >
static int poptmx::_uint_conversion (BClass *_val, const string &in)
Enumeration Type Documentation
enum poptmx::Kind
Type of the element in the table of the known options.
Enumerator:
OPTION
 Option.
ARGUMENT
 Argument.
NOTE
 Note.
MAN
 Manual page.
PROC
 Post-parse processing function.
Definition at line 164 of file poptmx.h.
Function Documentation
int POPTMX_API poptmx::_conversion (bool * _val, const string &)
Sets the value to true.
Parameters
_val value to be updated
Returns
true
Definition at line 1254 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (string * _val, const string & in)
Copies the `in` string into _val.
Parameters
_val value to be updated.
in New value.
Returns
true
Definition at line 1276 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (unsigned char * _val, const string & in)
Converts the string `in` into unsigned char _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1326 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (unsigned int * _val, const string & in)
Converts the string `in` into unsigned integer _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1483 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (long * _val, const string & in)
Converts the string `in` into long integer _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1507 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (short * _val, const string & in)
Converts the string `in` into short integer _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1417 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (unsigned long * _val, const string & in)
Converts the string `in` into unsigned long integer _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1528 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (long long * _val, const string & in)
Converts the string `in` into long long integer _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1550 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (char * _val, const string & in)
Converts the string `in` into char _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1298 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (unsigned short * _val, const string & in)
Converts the string `in` into unsigned short integer _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1438 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (unsigned long long * _val, const string & in)
Converts the string `in` into unsigned long long integer _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1598 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (float * _val, const string & in)
Converts the string `in` into float _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1647 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (int * _val, const string & in)
Converts the string `in` into integer _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1461 of file poptmx.cpp.
int POPTMX_API poptmx::_conversion (double * _val, const string & in)
Converts the string `in` into double float _val.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 1687 of file poptmx.cpp.
template<class BClass > OptionTable & poptmx::OptionTable::add (Kind _kind, BClass * _val, const char _char_name, const std::string & _long_name, const std::string & _short_desc, const std::string & _long_desc, const std::string & _dflt = ``) [inline, inherited]
Simplified interface to add the option into the table.
The interface to add the option into the table which argument's type has defined `bool _conversion (BClass * , const std::string &)` and `std::string type_desc (BClass*)` functions.
Parameters
_kind Kind of entry to add. In this context can be ::OPTION.
_val Option::val
_char_name Option::char_name
_long_name Option::long_name
_short_desc Option::short_desc
_long_desc Option::long_desc
Definition at line 478 of file poptmx.h.
References poptmx::OptionTable::add(), OPTION, throw_error(), and type_desc().
template<class BClass > OptionTable & poptmx::OptionTable::add (Kind _kind, BClass * _val, const std::string & _long_name, const std::string & _short_desc, const std::string & _long_desc, const std::string & _dflt = ``) [inline, inherited]
Simplified interface to add the argument into the table.
The interface to add into the table the argument which type has defined `bool _conversion (BClass * , const std::string &)` and `std::string type_desc (BClass*)` functions.
Parameters
_kind Kind of entry to add. In this context can be ::ARGUMENT.
_val Option::val
_long_name Option::long_name
_short_desc Option::short_desc
_long_desc Option::long_desc
Definition at line 498 of file poptmx.h.
References poptmx::OptionTable::add(), ARGUMENT, throw_error(), and type_desc().
template<class BClass > OptionTable & poptmx::OptionTable::add (Kind _kind, std::vector< BClass > * _val, const std::string & _long_name, const std::string & _short_desc, const std::string & _long_desc, const std::string & _dflt = ``) [inline, inherited]
Simplified interface to add multiple-appearing argument into the table.
The interface to add the multi-acceptable argument into the table. The argument's type must have defined `bool _conversion (BClass * , const std::string &)` and `std::string type_desc (BClass*)` functions.
Parameters
_kind Kind of entry to add. In this context can be ::ARGUMENT
_val Option::val
_long_name Option::long_name
_short_desc Option::short_desc
_long_desc Option::long_desc
Definition at line 564 of file poptmx.h.
References poptmx::OptionTable::add(), ARGUMENT, throw_error(), and type_desc().
template<class BClass > OptionTable & poptmx::OptionTable::add (Kind _kind, std::vector< BClass > * _val, const char _char_name, const std::string & _long_name, const std::string & _short_desc, const std::string & _long_desc, const std::string & _dflt = ``) [inline, inherited]
Simplified interface to add multiple-appearing option into the table.
The interface to add the multi-acceptable option into the table. The option's argument's type has defined `bool _conversion (BClass * , const std::string &)` and `std::string type_desc (BClass*)` functions.
Parameters
_kind Kind of entry to add. In this context can be ::OPTION
_val Option::val
_char_name Option::char_name
_long_name Option::long_name
_short_desc Option::short_desc
_long_desc Option::long_desc
Definition at line 543 of file poptmx.h.
References poptmx::OptionTable::add(), OPTION, throw_error(), and type_desc().
template<class BClass > int poptmx::arr_conversion (void * _val, const std::string & in) [inline]
The layer between the real type-overloaded function which parses the string into value and the function which first converts the string into a temp value and then inserts it into the array of values. Needed here to be inserted into the Option entry Option::convert (of type bool (*)(void*, const std::string &)).
Parameters
_val The array to accept the newly parsed value from the `in` string.
in The string to be parsed into the value.
Returns
true if the conversion is successful and false if failed.
Definition at line 522 of file poptmx.h.
template<class BClass > int poptmx::conversion (void * _val, const std::string & in) [inline]
The layer between the real type-overloaded function which parses the string into value and the function which can be inserted into the Option entry as Option::convert (of type bool (*)(void*, const std::string &))
Parameters
_val The value to be updated when parsing the `in` string.
in The string to be parsed into the _val.
Returns
true if the conversion is successful and false if failed.
Definition at line 461 of file poptmx.h.
References _conversion().
static void poptmx::throw_error (const std::string & mod, const std::string & msg) [inline, static]
Constructs the error, reports and then throws it.
Parameters
mod Module where the error happened.
msg Description.
Definition at line 139 of file poptmx.h.
References poptmx::Err::ERR, and poptmx::Err::report().
std::string POPTMX_API poptmx::type_desc (long long *)
Prints type name.
Returns
type name.
Definition at line 1583 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (string *)
Prints type name.
Returns
type name.
Definition at line 1284 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (float *)
Prints type name.
Returns
type name.
Definition at line 1673 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (double *)
Prints type name.
Returns
type name.
Definition at line 1713 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (unsigned int *)
Prints type name.
Returns
type name.
Definition at line 1490 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (int *)
Prints type name.
Returns
type name.
Definition at line 1468 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (char *)
Prints type name.
Returns
type name.
Definition at line 1310 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (bool *)
Prints type name.
Returns
type name.
Definition at line 1262 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (long *)
Prints type name.
Returns
type name.
Definition at line 1514 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (unsigned long long *)
Prints type name.
Returns
type name.
Definition at line 1631 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (unsigned short *)
Prints type name.
Returns
type name.
Definition at line 1445 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (unsigned char *)
Prints type name.
Returns
type name.
Definition at line 1338 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (unsigned long *)
Prints type name.
Returns
type name.
Definition at line 1535 of file poptmx.cpp.
std::string POPTMX_API poptmx::type_desc (short *)
Prints type name.
Returns
type name.
Definition at line 1424 of file poptmx.cpp.
static Err poptmx::warn (const std::string & mod, const std::string & msg) [inline, static]
Constructs the warning and reports it.
Parameters
mod Module where the error happened
msg Description
Returns
the error generated in warning.
Definition at line 153 of file poptmx.h.
References poptmx::Err::report(), and poptmx::Err::WARN.