Image and data file handling.
Functions
float COMMON_API PixelSize (const Path &filename)
Pixel size of the image.
Shape COMMON_API ImageSizes (const Path &filename)
Image sizes.
void COMMON_API ImageSizes (const Path &filename, int *width, int *hight)
Image sizes.
void COMMON_API BadShape (const Path &filename, const Shape &shp)
Check the shape of the image.
void COMMON_API ReadImage (const Path &filename, Map &storage)
Load image from preopened object.
void COMMON_API ReadImage (const Path &filename, Map &storage, const Shape &shp)
Load image checking the shape.
void COMMON_API ReadImageLine (const Path &filename, Line &storage, int idx)
Load one line of the image.
void COMMON_API ReadImageLine (const Path &filename, Line &storage, int idx, const Shape &shp)
Load one line of the image.
void COMMON_API ReadImageLine (const Path &filename, Map &storage, const std::vector< int > &idxs)
Load several lines of the image.
void COMMON_API ReadImageLine (const Path &filename, Map &storage, const std::vector< int > &idxs, const Shape &shp)
Load several lines of the image.
void COMMON_API SaveImage (const Path &filename, const Map &storage, bool saveint=false)
Save the array into image.
void COMMON_API SaveImage (const Path &filename, const Map &storage, float minval, float maxval)
Save the array into integer image.
void COMMON_API LoadData (const Path filename,...)
Loads any amount of lines from data file.
void COMMON_API SaveData (const Path filename,...)
Save any amount of lines into data file.
Detailed Description
Loading, saving and other possible operations with the image/data -> array -> image/data conversions.
Function Documentation
void COMMON_API BadShape (const Path & filename, const Shape & shp)
Check the shape of the image.
Throws error if the shape of the image is not equal to ::shp.
Parameters
filename Image filename.
shp The expected shape.
Definition at line 675 of file common.cpp.
References ImageSizes(), throw_error(), and toString().
Referenced by ReadImage(), and ReadImageLine().
Shape COMMON_API ImageSizes (const Path & filename)
Image sizes.
Reads image size and returns them as the Shape vector.
Parameters
filename Image filename.
Returns
Image sizes.
Definition at line 654 of file common.cpp.
References throw_error().
Referenced by AqSeries::AqSeries(), BadShape(), getLine(), ImageSizes(), and main().
void COMMON_API ImageSizes (const Path & filename, int * width, int * hight)
Image sizes.
Read image sizes and return them as width and hight.
Parameters
filename Image filename.
width Width of the image.
hight Height of the image.
Definition at line 667 of file common.cpp.
References ImageSizes().
void COMMON_API LoadData (const Path filename, ...)
Loads any amount of lines from data file.
Parameters
filename the name of the data file.
... Any number of the lines. Be careful: I supposed that all arguments are of type const Line*, a null pointer must be passed as the last such argument.
Definition at line 1366 of file common.cpp.
References throw_error(), toString(), and warn().
Referenced by EDEIprocess::loadRC().
float COMMON_API PixelSize (const Path & filename)
Pixel size of the image.
Calculated from the dpi (dots per inch).
Parameters
filename Image filename.
Returns
pixel size in micron.
Definition at line 627 of file common.cpp.
References warn().
void COMMON_API ReadImage (const Path & filename, Map & storage)
Load image from preopened object.
Similar to ReadImage(), but uses preopened image object to read.
Parameters
filename Image filename.
storage Array to load the image into.
Definition at line 790 of file common.cpp.
References ReadImage_FI(), ReadImage_IM(), CtasErr::type(), and CtasErr::WARN.
Referenced by main(), ReadImage(), and ReadImageLine().
void COMMON_API ReadImage (const Path & filename, Map & storage, const Shape & shp)
Load image checking the shape.
Same as ReadImage(const Path & , Map &), but checks the image shape before loading and throws the error if the shape is different from :::shp.
Parameters
filename Image filename.
storage Array to load the image into.
shp The expected shape.
Definition at line 802 of file common.cpp.
References BadShape(), and ReadImage().
void COMMON_API ReadImageLine (const Path & filename, Line & storage, int idx, const Shape & shp)
Load one line of the image.
Same as ReadImageLine(const Path &, Line &, int), but checks the image shape before loading and throws the error if the shape is different from ::shp.
Parameters
filename File to read the image from.
storage Array to load the image into.
idx The index of the line to be read.
shp The expected shape.
Definition at line 937 of file common.cpp.
References BadShape(), and ReadImageLine().
void COMMON_API ReadImageLine (const Path & filename, Map & storage, const std::vector< int > & idxs)
Load several lines of the image.
Reads lines of the image which are found in the ::idxs vector. If a line in the ::idxs is outside the image size then warns and fills the corresponding line with zeros. The lines are stored in the order they found in the ::idx vector. Array ::storage is resized to contain all lines. If the ::idxs array is empty - reads the whole image.
Parameters
filename File to read the image from.
storage Array to load the image into.
idxs vector of lines to be read. If empty, reads the whole image.
Definition at line 1041 of file common.cpp.
References ReadImage(), ReadImageLine_FI(), ReadImageLine_IM(), CtasErr::type(), and CtasErr::WARN.
void COMMON_API ReadImageLine (const Path & filename, Map & storage, const std::vector< int > & idxs, const Shape & shp)
Load several lines of the image.
Same as ReadImageLine(const Path &, Map &, const std::vector<int> &), but checks the image shape before loading and throws the error if the shape is different from ::shp.
Parameters
filename File to read the image from.
storage Array to load the image into.
idxs vector of lines to be read. If empty - reads the whole image.
shp The expected shape.
Definition at line 1061 of file common.cpp.
References BadShape(), and ReadImageLine().
void COMMON_API ReadImageLine (const Path & filename, Line & storage, int idx)
Load one line of the image.
Reads one line of the image from the file, resizes the array to fit and stores the line into the array.
Parameters
filename File to read the image from.
storage Array to load the image into.
idx The index of the line to be read.
Definition at line 924 of file common.cpp.
References ReadImageLine_FI(), ReadImageLine_IM(), CtasErr::type(), and CtasErr::WARN.
Referenced by AqSeries::darkCurrent(), getLine(), main(), AqSeries::projection(), and ReadImageLine().
void COMMON_API SaveData (const Path filename, ...)
Save any amount of lines into data file.
Parameters
filename the name of the data file.
... Any number of the lines. Be careful: I supposed that all arguments are of type const Line*, a null pointer must be passed as the last such argument.
Definition at line 1314 of file common.cpp.
References throw_error(), toString(), and warn().
Referenced by EDEIprocess::saveFD().
void COMMON_API SaveImage (const Path & filename, const Map & storage, bool saveint = false)
Save the array into image.
Stores the array in the float-point TIFF or integer image depending. on requested type. Be careful: limited number of editors/viewers/analyzers support float-point format.
Parameters
filename the name of the image file image.
storage the array to be written to the image.
saveint save image as 16-bit integer.
Definition at line 1287 of file common.cpp.
References SaveImageFP(), and SaveImageINT().
Referenced by main().
void COMMON_API SaveImage (const Path & filename, const Map & storage, float minval, float maxval)
Save the array into integer image.
Stores the array in the integer-based image. If minval is equal to maxval then the minimum and maximum values of the array data corresponds to black and white respectively.
Parameters
filename the name of the image file image.
storage the array to be written to the image.
minval the value corresponding to black.
maxval the value corresponding to white.
Definition at line 1293 of file common.cpp.
References SaveImageINT().