Error handling.
Classes
class CtasErr
Error type.
Functions
void COMMON_API throw_error (const std::string &mod, const std::string &msg)
Constructs the error, reports and then throws it.
void COMMON_API throw_bug (const std::string &mod)
Reports and throws the bug.
CtasErr COMMON_API warn (const std::string &mod, const std::string &msg)
Constructs the warning and reports it.
void COMMON_API exit_on_error (const std::string &mod, const std::string &msg)
Constructs the error, reports and then exits.
Detailed Description
Functions in this group are used for the error parsing, printing, throwing and so on.
Function Documentation
void COMMON_API exit_on_error (const std::string & mod, const std::string & msg)
Constructs the error, reports and then exits.
Parameters
mod Module where the error happened
msg Description
Definition at line 100 of file common.cpp.
References CtasErr::FATAL, and CtasErr::report().
Referenced by clargs::clargs(), main(), and proj_info::proj_info().
void COMMON_API throw_bug (const std::string & mod)
Reports and throws the bug.
Constructs the error with the message that it must never happen, reports and then throws it.
Parameters
mod Module where the error happened.
Definition at line 88 of file common.cpp.
References throw_error().
Referenced by find_minus(), find_plus(), msign(), Interp::name(), Filter::name(), and Contrast::name().
void COMMON_API throw_error (const std::string & mod, const std::string & msg)
Constructs the error, reports and then throws it.
Parameters
mod Module where the error happened.
msg Description.
Definition at line 81 of file common.cpp.
References CtasErr::ERR, and CtasErr::report().
Referenced by _conversion(), poptmx::OptionTable::add(), CTrec::addLine(), AqSeries::AqSeries(), BadShape(), Contrast::Contrast(), poptmx::OptionTable::count(), Dcenter::Dcenter(), DEIprocess::DEIprocess(), poptmx::OptionTable::desc(), EDEIprocess::EDEIprocess(), Experiment::Experiment(), IPCprocess::extract(), EDEIprocess::extract(), DEIprocess::extract(), Filter::fill(), Filter::Filter(), find_minus(), find_plus(), flatfield(), getLine(), has_one_peak(), ImageSizes(), SinoS::index(), AqSeries::index(), Interp::Interp(), IPCexp::IPCexp(), IPCprocess::IPCprocess(), line_distributor::line_distributor(), LoadData(), EDEIprocess::loadRC(), main(), poptmx::Option::Option(), poptmx::OptionTable::parse(), poptmx::Option::parse(), CTrec::pixels(), proj_info::proj_info(), project_sino(), AqSeries::projection(), propagate(), ReadImage_IM(), ReadImageLine_FI(), ReadImageLine_IM(), CTrec::reconstruct(), poptmx::OptionTable::replacePointers(), SaveData(), SaveImageINT_IM(), SinoS::SinoS(), tempfile(), throw_bug(), Path::throw_unextracted(), and ts_add().
CtasErr COMMON_API warn (const std::string & mod, const std::string & msg)
Constructs the warning and reports it.
Parameters
mod Module where the error happened
msg Description
Returns
the error generated in warning.
Definition at line 93 of file common.cpp.
References CtasErr::report(), and CtasErr::WARN.
Referenced by poptmx::OptionTable::add(), CTrec::choose_algorithm(), Dcenter::Dcenter(), FImageLoader(), LoadData(), EDEIprocess::loadRC(), main(), nof_threads(), poptmx::OptionTable::parse(), PixelSize(), proj_info::proj_info(), propagate(), ReadImage_FI(), ReadImage_IM(), ReadImageLine_FI(), ReadImageLine_IM(), SaveData(), SaveImageINT_FI(), SinoS::SinoS(), slice_str2vec(), str2n(), and tempfile().