Experiment.
Classes
class ABSexp
Class which projections from the input data of the absorption-based experiment.
class DEIexp
Class which extracts DEI-processed projections from the input data.
class EDEIexp
Class which extracts EDEI-processed projections from the input data.
class AqSeries
Parsing file of the acquisition series.
class Experiment
Parent abstract class for various experimental techniques.
class SinoS
Projections storage.
class Dcenter
Class to deal with the rotation center (read DcenterOptionDesc).
class IPCexp
Class which extracts IPC-processed projections from the input data.
Functions
std::string EXPERIMENT_API mask2format (const std::string &mask, int maxslice)
Converts the mask string to the format string.
std::vector< int > EXPERIMENT_API slice_str2vec (const std::string &sliceS, int hight)
Constructs the array of slices.
std::string EXPERIMENT_API type_desc (Dcenter *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool EXPERIMENT_API _conversion (Dcenter *_val, const std::string &in)
Converts the string `in` into the Dcenter _val. To be used in the CLI parsing via `poptmx` library.
Variables
EXPERIMENT_API const std::string MaskDesc
Description of the output result mask.
EXPERIMENT_API const std::string SliceOptionDesc
Description of the option giving the string of slices.
EXPERIMENT_API const std::string DcenterOptionDesc
Description of the option giving the Dcenter type.
static const std::string ABSexp::modname = `ABS experiment`
Name of the module.
Detailed Description
Functions and classes responsible for the processing a series of images .
#ifdef _H_EXPERIMENT_H_
Function Documentation
bool EXPERIMENT_API _conversion (Dcenter * _val, const std::string & in)
Converts the string `in` into the Dcenter _val. To be used in the CLI parsing via `poptmx` library.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 810 of file experiment.cpp.
std::string EXPERIMENT_API mask2format (const std::string & mask, int maxslice)
Converts the mask string to the format string.
Parameters
mask Mask string (read MaskDesc).
maxslice Maximum allowed slice (total number of slices).
Returns
The format string which ready to be used with the fmt2s() function.
Definition at line 315 of file experiment.cpp.
References toString().
Referenced by main().
std::vector<int> EXPERIMENT_API slice_str2vec (const std::string & sliceS, int hight)
Constructs the array of slices.
Constructs the array of slices to be processed from the slice string (read SliceOptionDesc for more details).
Parameters
sliceS Input SliceOptionDesc `slice string`.
hight Height of the input projection(s).
Returns
The vector consisting of the numbers of slices to be processed. The vector is sorted and duplicates are removed.
Definition at line 392 of file experiment.cpp.
References rmadd(), str2n(), toString(), and warn().
Referenced by main().
std::string EXPERIMENT_API type_desc (Dcenter *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
Returns
type name.
Definition at line 805 of file experiment.cpp.
Variable Documentation
EXPERIMENT_API const std::string DcenterOptionDesc
Description of the option giving the Dcenter type.
Definition at line 785 of file experiment.cpp.
Referenced by clargs::clargs().
EXPERIMENT_API const std::string MaskDesc
Description of the output result mask.
Definition at line 296 of file experiment.cpp.
Referenced by clargs::clargs().
const std::string ABSexp::modname = `ABS experiment` [static, private, inherited]
Name of the module.
Definition at line 45 of file abs.h.
EXPERIMENT_API const std::string SliceOptionDesc
Description of the option giving the string of slices.
Definition at line 333 of file experiment.cpp.
Referenced by clargs::clargs().