EDEI processing.
Classes
class Interp
Auxiliary class: just wrap around inter_tp enumeration.
struct EDEIoptions
Structure with the elements needed for the initialization of the EDEIprocess.
class EDEIprocess
Store, process read RCstaff::RCoption() `RC`, read RCstaff::FDoption() `FD`, extract contrasts.
class EDEIexp
Class which extracts EDEI-processed projections from the input data.
Functions
bool EDEI_API operator== (const Interp &a, const Interp &b)
Compare interpretations.
bool EDEI_API operator!= (const Interp &a, const Interp &b)
Compare interpretations.
EDEI_API std::string type_desc (Interp *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
EDEI_API bool _conversion (Interp *_val, const std::string &in)
Converts the string `in` into the Interp _val. To be used in the CLI parsing via `poptmx` library.
std::string type_desc (EDEIprocess::Component *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool EDEI_API _conversion (EDEIprocess::Component *_val, const std::string &in)
Converts the string `in` into the EDEIprocess::Component _val. To be used in the CLI parsing via `poptmx` library.
std::string toString (EDEIprocess::Component comp)
static int find_minus (float Gm, Interp mpinter, const Line &alpha, const Line &RC)
static int find_plus (float Gp, Interp mpinter, const Line &alpha, const Line &RC)
static bool has_one_peak (const Line &arr)
static int msign (float val)
static void filterf (Line &arr)
static float findindex (float val, const Line &arr)
static float findvalue (float index, const Line &arr)
static int imin3 (int a, int b, int c)
template<int N_rank>
void EDEIprocess::extract (const blitz::Array< float, N_rank > &minus, const blitz::Array< float, N_rank > &plus, Component comp, blitz::Array< float, N_rank > &out) const
The same as ::extract, but works on array.
std::string Interp::name () const
Prints name.
inter_tp Interp::type () const
The interpretation type.
Interp::Interp (inter_tp _mpinter=REFLECT)
Constructor.
Interp::Interp (const std::string &_name)
Constructor from name.
poptmx::OptionTable EDEIoptions::options ()
Constructor.
EDEIprocess::EDEIprocess (const Path &RCname, float _Gm, float _Gp, Interp _mpinter, bool _smooth, float _acof)
Constructor.
float EDEIprocess::extract (float minus, float plus, Component comp) const
void EDEIprocess::loadRC (const Path &filename) const
Loads RC.
void EDEIprocess::saveFD (const Path &filename) const
Save read RCstaff::FDoption() `FD`.
Variables
EDEI_API const std::string InterpOptionDesc
Description of the option giving the Interp type.
static const std::string EDEIexp::modname = `EDEI experiment`
Name of the module.
static const std::string Interp::optionDesc = ` intensities and interprets the values as the normalized ones.`
Description of the type.
static const std::string EDEIoptions::fdOptionDesc = ` $\\alpha(x)$ position.`
Description of the FD option.
static const std::string EDEIoptions::fdOptionShortDesc = `File containing processed RC used inside the EDEI.`
Short description of the FD option.
static const std::string EDEIoptions::rcOptionDesc = ` radians and Y-axis in reflectivity.`
Description of the RC option.
static const std::string EDEIoptions::rcOptionShortDesc = `Input file containing the RC of the analyzer.`
Short description of the RC option.
static const std::string EDEIprocess::modname = `RC arguments`
Module name.
static const std::string EDEIprocess::componentDesc = `R, REF, REFRACTION - for the refraction component`
Description of the ::Component.
Detailed Description
Functions in this group are used to process read RCstaff::RCoption() `RC` and/or read RCstaff::FDoption() `FD` data files and extract the components from two image contrasts via the EDEI method
Function Documentation
bool _conversion (Interp * _val, const std::string & in)
Converts the string `in` into the Interp _val. To be used in the CLI parsing via `poptmx` library.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 111 of file ledei.cpp.
bool _conversion (EDEIprocess::Component * _val, const std::string & in)
Converts the string `in` into the EDEIprocess::Component _val. To be used in the CLI parsing via `poptmx` library.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 204 of file ledei.cpp.
References EDEIprocess::ABS, EDEIprocess::REF, throw_error(), and upper().
EDEIprocess::EDEIprocess (const Path & RCname, float _Gm, float _Gp, Interp _mpinter, bool _smooth, float _acof) [inherited]
Constructor.
Parameters
RCname Name of the file containing the read RCstaff::RCoption() `RC` of the analyzer.
_Gm Value determining the minus position.
_Gp Value determining the plus position.
_mpinter Interpretation of the ::_Gm, ::_Gp.
_smooth Smooth RC to avoid non-mono regions.
_acof X-axis (angle) conversion factor.
Definition at line 504 of file ledei.cpp.
References EDEIprocess::AL, EDEIprocess::function_size, EDEIprocess::loadRC(), EDEIprocess::modname, EDEIprocess::PM, and throw_error().
template<int N_rank> void EDEIprocess::extract (const blitz::Array< float, N_rank > & minus, const blitz::Array< float, N_rank > & plus, Component comp, blitz::Array< float, N_rank > & out) const [inherited]
The same as ::extract, but works on array.
Parameters
minus Array of the minus intensities.
plus Array of plus intensities.
comp Component to be extracted.
out Array of the extracted component depending on the ::comp.
Definition at line 265 of file edei.h.
References EDEIprocess::extract(), EDEIprocess::modname, and throw_error().
float EDEIprocess::extract (float minus, float plus, Component comp) const [inherited]
Extracts refraction component from the intensities recorded on both sides of the RC.
Parameters
minus contrast in minus position.
plus contrast in plus position.
comp component to be extracted.
Returns
refraction component.
Definition at line 526 of file ledei.cpp.
References EDEIprocess::ABS, EDEIprocess::AL, EDEIprocess::function_size, and EDEIprocess::PM.
Referenced by EDEIprocess::extract(), main(), and EDEIexp::projection().
static void filterf (Line & arr) [inline, static]
Smooth the array.
Performs very primitive smoothing of the array values.
Parameters
arr array to smooth.
Definition at line 398 of file ledei.cpp.
References msign().
Referenced by EDEIprocess::loadRC().
static int find_minus (float Gm, Interp mpinter, const Line & alpha, const Line & RC) [static]
Determines index of the minus position.
Finds the actual index of the minus position on the RC from the general value ::Gm and it's interpretation method.
Parameters
Gm Value determining the minus position
mpinter It's interpretation.
alpha angles $\alpha$ representing X-axis of the read RCstaff::RCoption() `RC`.
RC actual recorded intensities of the read RCstaff::RCoption() `RC` (Y-axis).
Returns
Index of the minus position in the RC arrays.
Definition at line 233 of file ledei.cpp.
References Interp::ALPHA, Interp::INTENS, Interp::NUMBER, Interp::REFLECT, throw_bug(), throw_error(), and toString().
Referenced by EDEIprocess::loadRC().
static int find_plus (float Gp, Interp mpinter, const Line & alpha, const Line & RC) [static]
Determines index of the plus position.
Finds the actual index of the plus position on the RC from the general value ::Gm and it's Interpretation method.
Parameters
Gp Value determining the plus position
mpinter It's Interpretation.
alpha angles $\alpha$ representing X-axis of the read RCstaff::RCoption() `RC`.
RC actual recorded intensities of the read RCstaff::RCoption() `RC` (Y-axis).
Returns
Index of the plus position in the RC arrays.
Definition at line 301 of file ledei.cpp.
References Interp::ALPHA, Interp::INTENS, Interp::NUMBER, Interp::REFLECT, throw_bug(), throw_error(), and toString().
Referenced by EDEIprocess::loadRC().
static float findindex (float val, const Line & arr) [static]
Finds the index of the value.
Finds the index of the array's value which is closest to the ::val. The arrays values must be monotonously growing. Float part of the returned number tells the relative position of the index between two arrays values.
Parameters
val value who's index to find.
arr array where to find the index.
Returns
index of the value in the array closest to ::val.
Definition at line 419 of file ledei.cpp.
Referenced by EDEIprocess::loadRC().
static float findvalue (float index, const Line & arr) [static]
Returns the value of the array.
Returns linear Interpolation of the array value.
Parameters
index index of the value.
arr array with values.
Returns
array value.
Definition at line 451 of file ledei.cpp.
Referenced by EDEIprocess::loadRC().
static bool has_one_peak (const Line & arr) [static]
Tells if the function represented by the array has only one peak.
Parameters
arr - array to find the peak in.
Returns
true if there is only one peak in the array, false otherwise.
Definition at line 363 of file ledei.cpp.
References throw_error().
Referenced by EDEIprocess::loadRC().
static int imin3 (int a, int b, int c) [inline, static]
Returns minimum of three integers.
Parameters
a In 1
b In 2
c In 3
Returns
Minimum of a, b and c.
Definition at line 470 of file ledei.cpp.
Referenced by EDEIprocess::loadRC().
Interp::Interp (inter_tp _mpinter = REFLECT) [inherited]
Constructor.
Parameters
_mpinter Interpretation type.
Definition at line 64 of file ledei.cpp.
Interp::Interp (const std::string & _name) [inherited]
Constructor from name.
Parameters
_name The name to be converted to the type.
Definition at line 69 of file ledei.cpp.
References Interp::ALPHA, Interp::INTENS, Interp::mpinter, Interp::name(), Interp::NUMBER, Interp::REFLECT, throw_error(), and upper().
void EDEIprocess::loadRC (const Path & filename) const [private, inherited]
Loads RC.
Loads read RCstaff::RCoption() `RC`, processes it and makes the class ready for the data extraction.
Parameters
filename read RCstaff::RCoption() `RC` file
Definition at line 543 of file ledei.cpp.
References EDEIprocess::acof, EDEIprocess::AL, filterf(), find_minus(), find_plus(), findindex(), findvalue(), EDEIprocess::function_size, EDEIprocess::Gm, EDEIprocess::Gp, has_one_peak(), imin3(), LoadData(), EDEIprocess::modname, EDEIprocess::mpinter, Interp::name(), Interp::NUMBER, EDEIprocess::PM, EDEIprocess::smooth, throw_error(), and warn().
Referenced by EDEIprocess::EDEIprocess().
static int msign (float val) [inline, static]
Returns the sign of the float value.
Parameters
val the value to determine the sign.
Returns
0 if value is 0.0, -1 if negative, +1 if positive.
Definition at line 382 of file ledei.cpp.
References throw_bug().
Referenced by filterf().
string Interp::name () const [inherited]
Prints name.
Prints the name of the interpretation type.
Returns
Printed name of the interpretation.
Definition at line 44 of file ledei.cpp.
References throw_bug().
Referenced by Interp::Interp(), EDEIprocess::loadRC(), and EDEIoptions::options().
bool operator!= (const Interp & a, const Interp & b)
Compare interpretations.
Parameters
a first Interp.
b second Interp.
Returns
false if the interpretations are equal, true otherwise.
Definition at line 101 of file ledei.cpp.
References Interp::type().
bool operator== (const Interp & a, const Interp & b)
Compare interpretations.
Parameters
a first Interp.
b second Interp.
Returns
true if the interpretations are equal, false otherwise.
Definition at line 97 of file ledei.cpp.
References Interp::type().
poptmx::OptionTable EDEIoptions::options () [inherited]
Constructor.
Option table.
Constructs and returns the option table.
Returns
Option table to be used via the poptmx library.
Definition at line 127 of file ledei.cpp.
References EDEIoptions::acof, poptmx::OptionTable::add(), poptmx::OptionTable::desc(), EDEIoptions::Gm, EDEIoptions::Gp, EDEIoptions::mpinter, Interp::name(), poptmx::NOTE, poptmx::OPTION, Interp::optionDesc, and toString().
void EDEIprocess::saveFD (const Path & filename) const [inherited]
Save read RCstaff::FDoption() `FD`.
Saves processed read RCstaff::FDoption() `FD` to file.
Parameters
filename Name for the file to save read RCstaff::FDoption() `FD` to.
Definition at line 623 of file ledei.cpp.
References EDEIprocess::AL, EDEIprocess::PM, and SaveData().
Referenced by main().
Interp::inter_tp Interp::type () const [inherited]
The interpretation type.
Returns
The interpretation type.
Definition at line 59 of file ledei.cpp.
Referenced by operator!=(), and operator==().
std::string type_desc (EDEIprocess::Component *) [inline]
Prints type name. To be used in the CLI parsing via `poptmx` library.
Returns
type name.
Definition at line 233 of file edei.h.
string type_desc (Interp *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
Returns
type name.
Definition at line 106 of file ledei.cpp.
Variable Documentation
const std::string EDEIprocess::componentDesc = `R, REF, REFRACTION - for the refraction component` [static, inherited]
Description of the ::Component.
Definition at line 211 of file edei.h.
const std::string EDEIoptions::fdOptionDesc = ` $\\alpha(x)$ position.` [static, inherited]
Description of the FD option.
Definition at line 153 of file edei.h.
const std::string EDEIoptions::fdOptionShortDesc = `File containing processed RC used inside the EDEI.` [static, inherited]
Short description of the FD option.
Definition at line 155 of file edei.h.
EDEI_API const std::string InterpOptionDesc
Description of the option giving the Interp type.
const std::string EDEIexp::modname = `EDEI experiment` [static, private, inherited]
Name of the module.
Definition at line 297 of file edei.h.
const string EDEIprocess::modname = `RC arguments` [static, private, inherited]
Module name.
Definition at line 187 of file edei.h.
Referenced by EDEIprocess::EDEIprocess(), EDEIprocess::extract(), and EDEIprocess::loadRC().
const std::string Interp::optionDesc = ` intensities and interprets the values as the normalized ones.` [static, inherited]
Description of the type.
Definition at line 85 of file edei.h.
Referenced by EDEIoptions::options().
const std::string EDEIoptions::rcOptionDesc = ` radians and Y-axis in reflectivity.` [static, inherited]
Description of the RC option.
Definition at line 152 of file edei.h.
const std::string EDEIoptions::rcOptionShortDesc = `Input file containing the RC of the analyzer.` [static, inherited]
Short description of the RC option.
Definition at line 154 of file edei.h.