Common tasks.
Classes
class ProgressBar
CLI progress bar (PB).
Functions
std::string COMMON_API upper (std::string str)
Convert string to upper case.
std::string COMMON_API lower (std::string str)
Convert string to lower case.
std::string COMMON_API toString (const std::string fmt,...)
Prints formatted message to string.
std::string toString (long double n)
Prints the value to string.
std::string toString (float n)
std::string toString (double n) { return toString(`%g`, n); }
std::string toString (long int n)
std::string toString (int n)
std::string toString (long unsigned n)
std::string toString (unsigned n)
std::string toString (const Shape &shp)
template<int N>
blitz::Array< float, N > & unzero (blitz::Array< float, N > &arr)
template<int N>
blitz::Array< float, N > unzero (const blitz::Array< float, N > &arr)
Variables
const std::string COMMON_API IntOptionDesc
Description of the -i, --int option used in many modules.
const std::string COMMON_API ResolutionOptionDesc
Description of the --resolution option used in many modules.
const std::string COMMON_API NeedForQuant
The note added to many options.
const std::string COMMON_API SeeAlsoList
Detailed Description
Small useful functions and constants used many times
Function Documentation
std::string COMMON_API lower (std::string str)
Convert string to lower case.
Parameters
str Input string.
Returns
New string which represents input string converted into the lower case.
Definition at line 408 of file common.cpp.
std::string toString (long double n) [inline]
Prints the value to string.
Parameters
n number to be printed
Returns
string with printed number
Definition at line 437 of file common.h.
std::string toString (float n) [inline]
std::string toString (double n) { return toString(`%g`, n); }
Definition at line 439 of file common.h.
std::string COMMON_API toString (const std::string fmt, ...)
Prints formatted message to string.
Like 'sprintf', but prints into the STL std::string
Parameters
fmt format string.
... whatever goes into the format string.
Returns
New STL string with the printed expression.
Definition at line 415 of file common.cpp.
Referenced by CTrec::addLine(), BadShape(), clargs::clargs(), ProgressBar::done(), IPCprocess::extract(), find_minus(), find_plus(), getLine(), SinoS::index(), AqSeries::index(), IPCprocess::IPCprocess(), LoadData(), main(), mask2format(), EDEIoptions::options(), DEIoptions::options(), CTrec::pixels(), proj_info::proj_info(), AqSeries::projection(), propagate(), ReadImageLine_FI(), ReadImageLine_IM(), CTrec::reconstruct(), SaveData(), SinoS::SinoS(), slice_str2vec(), tempfile(), and ProgressBar::update().
template<int N> blitz::Array<float,N>& unzero (blitz::Array< float, N > & arr)
Removes all (sub-)zeros from the array.
Parameters
arr the array to be processed.
Returns
processed input array.
Definition at line 487 of file common.h.
Referenced by CTrec::addLine(), main(), IPCexp::projection(), and CTrec::reconstruct().
template<int N> blitz::Array<float,N> unzero (const blitz::Array< float, N > & arr) [inline]
Removes all (sub-)zeros from the array.
Parameters
arr the array to be processed.
Returns
processed array.
Definition at line 510 of file common.h.
std::string COMMON_API upper (std::string str)
Convert string to upper case.
Parameters
str Input string.
Returns
New string which represents input string converted into the upper case.
Definition at line 402 of file common.cpp.
Referenced by _conversion(), Contrast::Contrast(), Filter::Filter(), Interp::Interp(), and poptmx::OptionTable::man().
Variable Documentation
const std::string COMMON_API IntOptionDesc
Description of the -i, --int option used in many modules.
Definition at line 367 of file common.cpp.
Referenced by clargs::clargs().
const std::string COMMON_API NeedForQuant
The note added to many options.
Definition at line 374 of file common.cpp.
const std::string COMMON_API ResolutionOptionDesc
Description of the --resolution option used in many modules.
Definition at line 378 of file common.cpp.
const std::string COMMON_API SeeAlsoList
Lists all manual pages in the package. This string to be added to every manual page.
Definition at line 384 of file common.cpp.
Referenced by clargs::clargs().