Flat field correction.
Functions
static float flatfield (float fg, float bg, float dc=0.0)
static void flatfield (Map &result, const Map &fg, const Map &bg)
static void flatfield (Map &result, const Map &fg, const Map &bg, const Map &dc)
Variables
const std::string IdealWorldOptionDesc = ` points where the ratio exceeds 1, are set to 1.`
Description of the option giving the --idealworld option.
Detailed Description
Functions which perform the flat field correction.
Function Documentation
static float flatfield (float fg, float bg, float dc = 0.0) [inline, static]
Performs the flat image subtraction.
Would be used only as the blitz::Array function.
Parameters
fg foreground intensity.
bg background intensity.
dc dark current intensity.
Returns
intensity of the pixel with the subtracted background.
Definition at line 53 of file flatfield.h.
Referenced by flatfield(), main(), and AqSeries::projection().
static void flatfield (Map & result, const Map & fg, const Map & bg, const Map & dc) [inline, static]
Performs the flat field subtraction on arrays.
Parameters
result resulting array.
fg foreground intensity.
bg background intensity.
dc dark current intensity.
Definition at line 90 of file flatfield.h.
References flatfield(), and throw_error().
static void flatfield (Map & result, const Map & fg, const Map & bg) [inline, static]
Performs the background subtraction on arrays.
Parameters
result resulting array.
fg foreground intensity.
bg background intensity.
Definition at line 67 of file flatfield.h.
References flatfield(), and throw_error().
Variable Documentation
const std::string IdealWorldOptionDesc = ` points where the ratio exceeds 1, are set to 1.`
Description of the option giving the --idealworld option.
Definition at line 130 of file flatfield.h.
Referenced by clargs::clargs().