Common classes.
Classes
class Path
Path in the directory structure.
class Contrast
Type of the input contrast.
Typedefs
typedef blitz::Array< float, 1 > Line
1D line with data.
typedef blitz::Array< float, 2 > Map
2D Array with data.
typedef blitz::Array< float, 3 > Volume
3D Array with data.
typedef blitz::TinyVector< long int, 2 > Shape
Shape of an 2D array.
Functions
std::string COMMON_API type_desc (Path *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool COMMON_API _conversion (Path *_val, const std::string &in)
Converts the string `in` into the Path _val. To be used in the CLI parsing via `poptmx` library.
Path COMMON_API upgrade (const Path &path, const std::string &addthis)
Upgrades the filename with an addition.
Path COMMON_API cdpath (const Path &dir, const Path &file)
Adds the path to the filename.
bool COMMON_API operator== (const Contrast &a, const Contrast &b)
Compare contrasts.
bool COMMON_API operator!= (const Contrast &a, const Contrast &b)
Compare contrasts.
std::string COMMON_API type_desc (Contrast *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool COMMON_API _conversion (Contrast *_val, const std::string &in)
Converts the string `in` into the Contrast _val. To be used in the CLI parsing via `poptmx` library.
bool operator== (const Shape &sh1, const Shape &sh2)
Compare shapes.
bool operator!= (const Shape &sh1, const Shape &sh2)
Compare shapes.
Detailed Description
Common type definitions, classes, structures, enums and their friends.
Typedef Documentation
typedef blitz::Array<float,1> Line
1D line with data.
One dimensional array of the ::float elements. Used for filters, sinogram's lines and so on.
Definition at line 313 of file common.h.
typedef blitz::Array<float,2> Map
2D Array with data.
Two dimensional array of the ::float elements. Used for sinograms, input and output images etc.
Definition at line 319 of file common.h.
typedef blitz::TinyVector<long int,2> Shape
Shape of an 2D array.
Definition at line 331 of file common.h.
typedef blitz::Array<float,3> Volume
3D Array with data.
Three dimensional array of the ::float elements.
Definition at line 324 of file common.h.
Function Documentation
bool COMMON_API _conversion (Path * _val, const std::string & in)
Converts the string `in` into the Path _val. To be used in the CLI parsing via `poptmx` library.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 258 of file common.cpp.
Referenced by _conversion(), and poptmx::conversion().
bool COMMON_API _conversion (Contrast * _val, const std::string & in)
Converts the string `in` into the Contrast _val. To be used in the CLI parsing via `poptmx` library.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 349 of file common.cpp.
Path COMMON_API cdpath (const Path & dir, const Path & file)
Adds the path to the filename.
If the filename is absolute then just returns it as is. If the filename is relative then prefixes it with the `dir` and returns.
Parameters
dir Path to be added.
file File name to be updated with the path.
Returns
Updated filename.
Definition at line 238 of file common.cpp.
References Path::bedir(), and Path::isabsolute().
Referenced by AqSeries::AqSeries(), and proj_info::proj_info().
bool operator!= (const Shape & sh1, const Shape & sh2) [inline]
Compare shapes.
Parameters
sh1 first shape.
sh2 second shape.
Returns
false if the shapes are equal, true otherwise.
Definition at line 353 of file common.h.
bool COMMON_API operator!= (const Contrast & a, const Contrast & b)
Compare contrasts.
Parameters
a first contrast.
b second contrast.
Returns
false if the contrasts are equal, true otherwise.
Definition at line 339 of file common.cpp.
References Contrast::contrast().
bool COMMON_API operator== (const Contrast & a, const Contrast & b)
Compare contrasts.
Parameters
a first contrast.
b second contrast.
Returns
true if the contrasts are equal, false otherwise.
Definition at line 333 of file common.cpp.
References Contrast::contrast().
bool operator== (const Shape & sh1, const Shape & sh2) [inline]
Compare shapes.
Parameters
sh1 first shape.
sh2 second shape.
Returns
true if the shapes are equal, false otherwise.
Definition at line 341 of file common.h.
std::string COMMON_API type_desc (Path *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
Returns
type name.
Definition at line 253 of file common.cpp.
Referenced by poptmx::OptionTable::add().
std::string COMMON_API type_desc (Contrast *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
Returns
type name.
Definition at line 344 of file common.cpp.
Path COMMON_API upgrade (const Path & path, const std::string & addthis)
Upgrades the filename with an addition.
Prefixes the base of the filename with the addition while the path to the file remains unchanged.
Parameters
path Path to upgrade.
addthis the upgrade string.
Returns
itself
Definition at line 232 of file common.cpp.
References Path::dir(), and Path::name().
Referenced by clargs::clargs().