Inline phase contrast (IPC).
Classes
class IPCprocess
class IPCexp
Class which extracts IPC-processed projections from the input data.
Functions
void IPC_API propagate (const CMap &tif, Map &out, float dd, float lambda, float dist)
void IPC_API simulateTif (CMap &tif, const Shape &sh, float bd, float theta, float dd, float lambda)
std::string type_desc (IPCprocess::Component *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool IPC_API _conversion (IPCprocess::Component *_val, const std::string &in)
Converts the string `in` into the IPCprocess::Component _val. To be used in the CLI parsing via `poptmx` library.
std::string toString (IPCprocess::Component comp)
Variables
static const std::string IPCexp::modname = `IPC experiment`
Name of the module.
Detailed Description
Where all functions needed for the IPC processing go.
Function Documentation
bool IPC_API _conversion (IPCprocess::Component * _val, const std::string & in)
Converts the string `in` into the IPCprocess::Component _val. To be used in the CLI parsing via `poptmx` library.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 20 of file lipc.cpp.
References IPCprocess::ABS, IPCprocess::PHS, throw_error(), and upper().
void IPC_API propagate (const CMap & tif, Map & out, float dd, float lambda, float dist)
Transfer of intensity.
Calculates the intensity distribution at the given distance from the object's transmission function (usually denoted as T(x,y)). The intensity is calculated as the square of the convolution of the Fresnel propagator and Transmission function.
Parameters
tif Input object's transmission function.
out The resulting intensity distribution.
dd Pixel size.
lambda Wavelength.
dist Object-to-detector distance.
Definition at line 129 of file lipc.cpp.
References I_C, throw_error(), toString(), and warn().
void IPC_API simulateTif (CMap & tif, const Shape & sh, float bd, float theta, float dd, float lambda)
Simulates transmission function.
Calculates an ideal transmission function of the object consisting of three enclosed spheres with different values of the complex refraction index.
Parameters
tif The resulting array with the transmission function.
sh Sizes of the array.
bd The ration between the absorption and refraction indeces ($\beta/\delta$).
theta Rotation angle of the object.
dd Pixel size.
lambda Wavelength.
Definition at line 180 of file lipc.cpp.
References I_C.
std::string type_desc (IPCprocess::Component *) [inline]
Prints type name. To be used in the CLI parsing via `poptmx` library.
Returns
type name.
Definition at line 177 of file ipc.h.
Variable Documentation
const std::string IPCexp::modname = `IPC experiment` [static, private, inherited]
Name of the module.
Definition at line 209 of file ipc.h.
Referenced by IPCexp::IPCexp().