DEI processing.
Classes
struct DEIoptions
Structure with the elements needed for the initialization of the DEIprocess.
class DEIprocess
Extract contrasts via DEI.
class DEIexp
Class which extracts DEI-processed projections from the input data.
Functions
std::string type_desc (DEIprocess::Component *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool _conversion (DEIprocess::Component *_val, const std::string &in)
Converts the string `in` into the DEIprocess::Component _val. To be used in the CLI parsing via `poptmx` library.
std::string toString (DEIprocess::Component comp)
template<int N_rank>
blitz::Array< float, N_rank > DEIprocess::extract (const blitz::Array< float, N_rank > &minus, const blitz::Array< float, N_rank > &plus, Component comp) const
The same as ::extract, but works on array.
DEIprocess::DEIprocess (float _Gm=1.0, float _Gp=-1.0, float _Rm=0.5, float _Rp=0.5)
Constructor.
float DEIprocess::extract (float minus, float plus, Component comp) const
Variables
static const std::string DEIexp::modname = `DEI experiment`
Name of the module.
static const std::string DEIprocess::modname = `DEI process`
Module name.
static const std::string DEIprocess::componentDesc = `R, REF, REFRACTION - for the refraction component`
Description of the ::Component.
Detailed Description
Functions in this group are used extract the components from two image contrasts via the DEI method
Function Documentation
bool _conversion (DEIprocess::Component * _val, const std::string & in) [inline]
Converts the string `in` into the DEIprocess::Component _val. To be used in the CLI parsing via `poptmx` library.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 140 of file dei.h.
References DEIprocess::ABS, DEIprocess::REF, throw_error(), and upper().
DEIprocess::DEIprocess (float _Gm = 1.0, float _Gp = -1.0, float _Rm = 0.5, float _Rp = 0.5) [inherited]
Constructor.
Parameters
_Rm Reflectivity in the minus position.
_Rp Reflectivity in the plus position.
_Gm Derivative of the RC in the minus position.
_Gp Derivative of the RC in the plus position.
Definition at line 51 of file ldei.cpp.
References DEIprocess::Gm, DEIprocess::Gp, DEIprocess::modname, and throw_error().
template<int N_rank> blitz::Array< float, N_rank > DEIprocess::extract (const blitz::Array< float, N_rank > & minus, const blitz::Array< float, N_rank > & plus, Component comp) const [inherited]
The same as ::extract, but works on array.
Parameters
minus Array of the minus intensities.
plus Array of plus intensities.
comp Component to be extracted.
Returns
Array of the extracted component depending on the ::comp.
Definition at line 174 of file dei.h.
References DEIprocess::extract(), DEIprocess::modname, and throw_error().
float DEIprocess::extract (float minus, float plus, Component comp) const [inherited]
Extracts absorption component from the intensities recorded on both sides of the RC.
Note. ::minus and ::plus must be non-negative. No check inside.
Parameters
minus Intensity in minus point of the RC.
plus Intensity in plus point of the RC.
comp Component to be extracted.
Returns
Absorption contrast ($ I/I_0$) or refraction angle depending on the ::comp.
Definition at line 82 of file ldei.cpp.
References DEIprocess::ABS, DEIprocess::Gm, DEIprocess::Gp, DEIprocess::Rm, and DEIprocess::Rp.
Referenced by DEIprocess::extract(), main(), and DEIexp::projection().
std::string type_desc (DEIprocess::Component *) [inline]
Prints type name. To be used in the CLI parsing via `poptmx` library.
Returns
type name.
Definition at line 129 of file dei.h.
Variable Documentation
const std::string DEIprocess::componentDesc = `R, REF, REFRACTION - for the refraction component` [static, inherited]
Description of the ::Component.
Definition at line 112 of file dei.h.
const std::string DEIexp::modname = `DEI experiment` [static, private, inherited]
Name of the module.
Definition at line 204 of file dei.h.
const string DEIprocess::modname = `DEI process` [static, private, inherited]
Module name.
Definition at line 98 of file dei.h.
Referenced by DEIprocess::DEIprocess(), and DEIprocess::extract().