CT and TS reconstruction.
Classes
class Filter
Filtering window function.
class CTrec
CT reconstruction class.
Functions
bool KERNEL_API operator== (const Filter &a, const Filter &b)
Compare filters.
bool KERNEL_API operator!= (const Filter &a, const Filter &b)
Compare filters.
std::string KERNEL_API type_desc (Filter *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool KERNEL_API _conversion (Filter *_val, const std::string &in)
Converts the string `in` into the Filter _val. To be used in the CLI parsing via `poptmx` library.
void KERNEL_API ts_add (Map &projection, Map &result, const Filter &filter, const float center, const Contrast contrast, const float angle, const int plane)
long KERNEL_API nof_threads (long _threads=0)
Number of threads for the process.
Variables
KERNEL_API const std::string FilterOptionDesc
Description of the option giving the Filter type.
KERNEL_API const std::string CenterOptionDesc
Description of the option giving the rotation center.
Detailed Description
Where actual Computed Tomography and Tomosynthesis reconstruction is done.
Function Documentation
bool KERNEL_API _conversion (Filter * _val, const std::string & in)
Converts the string `in` into the Filter _val. To be used in the CLI parsing via `poptmx` library.
Parameters
_val value to be updated.
in string to be parsed.
Returns
true if success, false otherwise.
Definition at line 286 of file kernel.cpp.
References _conversion().
long KERNEL_API nof_threads (long _threads = 0)
Number of threads for the process.
Parameters
_threads Requested number of threads (0 for auto).
Returns
Number of threads for the architecture where the process is running if automatic number of threads was requested and just _threads if set in stone.
Definition at line 56 of file kernel.cpp.
References warn().
Referenced by CTrec::threads().
bool KERNEL_API operator!= (const Filter & a, const Filter & b)
Compare filters.
Parameters
a first filter.
b second filter.
Returns
false if the filters are equal, true otherwise.
Definition at line 257 of file kernel.cpp.
References Filter::filter().
bool KERNEL_API operator== (const Filter & a, const Filter & b)
Compare filters.
Parameters
a first filter.
b second filter.
Returns
true if the filters are equal, false otherwise.
Definition at line 252 of file kernel.cpp.
References Filter::filter().
void KERNEL_API ts_add (Map & projection, Map & result, const Filter & filter, const float center, const Contrast contrast, const float angle, const int plane)
Add one projection to the TS image.
The projection array is modified during the reconstruction: each line in the array is filtered (and converted to the field if refraction contrast is in use).
Parameters
projection Array with the projection (filtered projection on exit).
result Resulting array.
filter Fourier filter.
center deviation of the rotation axis from the center of the sinogram.
contrast Type of contrast
angle Angle at which the projection was recorded.
plane Plane of the reconstruction.
Definition at line 951 of file kernel.cpp.
References Contrast::ABS, Filter::fill(), filter_line(), Contrast::REF, and throw_error().
Referenced by main().
std::string KERNEL_API type_desc (Filter *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
Returns
type name.
Definition at line 281 of file kernel.cpp.
Variable Documentation
KERNEL_API const std::string CenterOptionDesc
Description of the option giving the rotation center.
Definition at line 1011 of file kernel.cpp.
KERNEL_API const std::string FilterOptionDesc
Description of the option giving the Filter type.
Definition at line 261 of file kernel.cpp.
Referenced by clargs::clargs().