/home/antonmx/work/projects/ctascmake/src/executables/ipc.cpp File Reference
#include `../common/common.h`
#include `../common/ipc.h`
#include `../common/poptmx.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'ct'.
Detailed Description
Author
antonmx <antonmx@gmail.com>
Date
Fri Jul 2 12:20:00 2010
Definition in file ipc.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'ct'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 152 of file ipc.cpp.
References IPCprocess::ABS, clargs::abs_name, clargs::alpha, clargs::command, clargs::dd, clargs::dgamma, clargs::dist, IPCprocess::extract(), clargs::lambda, IPCprocess::PHS, clargs::phs_name, ReadImage(), SaveImage(), clargs::SaveInt, unzero(), warn(), clargs::z0_name, and clargs::zD_name.