/home/antonmx/work/projects/ctascmake/src/common/kernel.cpp File Reference
Reconstruction implementation.
#include `kernel.h`
#include `poptmx.h`
#include <algorithm>
#include <numeric>
#include <time.h>
#include <pthread.h>
#include <gsl/gsl_sf_bessel.h>
#include <unistd.h>
Classes
class line_distributor
Thread distributor for the line-per-thread approach.
Functions
long nof_threads (long _threads)
Number of threads for the process.
bool operator== (const Filter &a, const Filter &b)
Compare filters.
bool operator!= (const Filter &a, const Filter &b)
Compare filters.
string type_desc (Filter *)
Prints type name. To be used in the CLI parsing via `poptmx` library.
bool _conversion (Filter *_val, const string &in)
Converts the string `in` into the Filter _val. To be used in the CLI parsing via `poptmx` library.
static void filter_line (Line &ln, const Line &f_win, const fftwf_plan *planF, const fftwf_plan *planB)
Applies FFT filter to one line.
static void project_line (const Line &sino, Map &result, float Theta, float center)
Projects one line onto the plane.
static void project_sino (const Map &sinogram, Map &result, float center)
Projects the sinogram.
static void * project_line_thr (void *_args)
Work for thread in the line-per-thread approach.
static void project_sino (const Map &sinogram, Map &result, float center, int threads)
Projects the sinogram using multithreaded approach.
void ts_add (Map &projection, Map &result, const Filter &filter, const float center, const Contrast contrast, const float angle, const int plane)
Variables
const string FilterOptionDesc = ` and their graphs can be found in the html documentation.`
Description of the option giving the Filter type.
static const int TR_conf = 1 << 16
The int to float conversion coefficient.
const string CenterOptionDesc = ` from the ImageMagick package with the -rotate option.`
Description of the option giving the rotation center.
Detailed Description
Reconstruction implementation.
Author
antonmx <antonmx@gmail.com>
Date
Thu Jul 17 13:22:00 2008
All functions which implement the actual reconstruction are defined here.
Definition in file kernel.cpp.
Function Documentation
static void filter_line (Line & ln, const Line & f_win, const fftwf_plan * planF, const fftwf_plan * planB) [inline, static]
Applies FFT filter to one line.
Parameters
ln Line to be filtered.
f_win Filter window.
planF Forward FFT plan.
planB Backward FFT plan.
Definition at line 330 of file kernel.cpp.
Referenced by CTrec::addLine_uni(), CTrec::reconstruct_uni(), and ts_add().
static void project_line (const Line & sino, Map & result, float Theta, float center) [static]
Projects one line onto the plane.
Parameters
sino Line to be projected.
result Plane to project to.
Theta Rotation angle.
center Deviation of the rotation center.
Definition at line 347 of file kernel.cpp.
References TR_conf.
Referenced by CTrec::addLine_uni(), project_line_thr(), and project_sino().
static void* project_line_thr (void * _args) [inline, static]
Work for thread in the line-per-thread approach.
Parameters
_args Arguments: distributor.
Returns
No return.
Definition at line 481 of file kernel.cpp.
References line_distributor::center(), line_distributor::distribute(), project_line(), and line_distributor::result().
Referenced by project_sino().
static void project_sino (const Map & sinogram, Map & result, float center, int threads) [inline, static]
Projects the sinogram using multithreaded approach.
Parameters
sinogram Sinogram to be projected
result The result to store the final projection.
center Rotation center.
threads Number of threads.
Definition at line 501 of file kernel.cpp.
References project_line_thr(), project_sino(), and throw_error().
static void project_sino (const Map & sinogram, Map & result, float center) [inline, static]
Projects the sinogram.
Parameters
sinogram Sinogram to be projected
result The result to store the final projection.
center Rotation center.
Definition at line 384 of file kernel.cpp.
References project_line().
Referenced by project_sino(), and CTrec::reconstruct_uni().
Variable Documentation
const int TR_conf = 1 << 16 [static]
The int to float conversion coefficient.
The calculations using float point numbers are much more expensive comparing to that of the integer type. In order to save time in the sensitive code it is possible to convert limited float numbers into integer ones, perform all linear calculations in the integer space and convert the result back to the float space. TR_conf gives the multiplication coefficient used to convert the float number limited to $\pm1.0$ (it is the cosine and sine of some value) to the integer.
Definition at line 319 of file kernel.cpp.
Referenced by project_line().