/home/antonmx/work/projects/ctascmake/src/executables/sino-abs.cpp File Reference
Makes sinograms from the list of foreground-background pairs.
#include <vector>
#include `../common/poptmx.h`
#include `../common/common.h`
#include `../common/flatfield.h`
#include `../common/experiment.h`
#include `../common/abs.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'sina'.
Detailed Description
Makes sinograms from the list of foreground-background pairs.
Author
antonmx <antonmx@asw062.synchrotron.org.au>
Date
Mon Apr 6 12:45:15 2009
Definition in file sino-abs.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'sina'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 114 of file sino-abs.cpp.
References clargs::beverbose, clargs::idealworld, clargs::listname, mask2format(), clargs::outmask, Experiment::pixels(), SaveImage(), clargs::SaveInt, SinoS::sino(), slice_str2vec(), clargs::slicedesc, Experiment::slices(), Experiment::thetas(), and toString().