/home/antonmx/work/projects/ctascmake/src/executables/sino-ipc.cpp File Reference
Makes sinograms from the EDEI input contrasts.
#include <vector>
#include `../common/common.h`
#include `../common/experiment.h`
#include `../common/ipc.h`
#include `../common/poptmx.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'sinr'.
Detailed Description
Makes sinograms from the EDEI input contrasts.
Author
antonmx <antonmx@gmail.com>
Date
Tue Jul 6 13:45:34 2010
Definition in file sino-ipc.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'sinr'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 173 of file sino-ipc.cpp.
References clargs::alpha, clargs::beverbose, clargs::contrast, clargs::dd, clargs::dgamma, clargs::dist, clargs::lambda, mask2format(), clargs::outmask, SaveImage(), clargs::SaveInt, AqSeries::shape(), SinoS::sino(), slice_str2vec(), clargs::slicedesc, toString(), clargs::z0_list, and clargs::zD_list.