/home/antonmx/work/projects/ctascmake/src/executables/sino.cpp File Reference
Make the sinogram.
#include `../common/common.h`
#include <vector>
#include `../common/poptmx.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'sino'.
Detailed Description
Make the sinogram.
Author
antonmx <antonmx@gmail.com>
Date
Mon Jul 21 10:09:31 2008
Main file for the program which reads the list of files forming the array of CT projections, picks one specified line from each of the and prepares the sinogram from these lines.
Todo Add possibility to make vertical sinograms.
Definition in file sino.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'sino'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 114 of file sino.cpp.
References clargs::beverbose, clargs::command, exit_on_error(), ImageSizes(), clargs::index, clargs::inlist, ReadImageLine(), SaveImage(), clargs::SaveInt, clargs::sinogram_name, toString(), and ProgressBar::update().