/home/antonmx/work/projects/ctascmake/src/executables/sino-edei.cpp File Reference
Makes sinograms from the EDEI input contrasts.
#include <vector>
#include `../common/common.h`
#include `../common/experiment.h`
#include `../common/edei.h`
Classes
struct clargs
Variables affected by the the command line arguments.
Functions
int main (int argc, char *argv[])
Main function for 'sinr'.
Detailed Description
Makes sinograms from the EDEI input contrasts.
Author
antonmx <antonmx@asw062.synchrotron.org.au>
Date
Mon Apr 6 12:46:41 2009
Definition in file sino-edei.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'sinr'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 131 of file sino-edei.cpp.
References EDEIoptions::acof, clargs::beverbose, clargs::contrast, clargs::edeiopt, EDEIoptions::Gm, EDEIoptions::Gp, mask2format(), clargs::Mlistname, EDEIoptions::mpinter, clargs::outmask, Experiment::pixels(), clargs::Plistname, EDEIoptions::RCname, SaveImage(), clargs::SaveInt, SinoS::sino(), slice_str2vec(), clargs::slicedesc, Experiment::slices(), EDEIoptions::smooth, Experiment::thetas(), and toString().