proj_info Struct Reference
Parses input data file.
Public Member Functions
proj_info (const string &data_name)
Constructor.
bool advance ()
Public Attributes
vector< pair< float, string > > list
List containing the angle-file pairs.
string name
Last file name met in the file.
float angle
Last acquisition angle in the file.
unsigned icur
Current element.
Detailed Description
Parses input data file. This structure parses the strings from the input data file and stores the result in self.
Definition at line 131 of file ts.cpp.
Constructor & Destructor Documentation
proj_info::proj_info (const string & data_name) [inline]
Constructor.
Parses the input file and prepares for work
Parameters
data_name The data file to be parsed. Read TSconfigDesc.
Definition at line 143 of file ts.cpp.
References angle, cdpath(), exit_on_error(), icur, list, name, throw_error(), toString(), and warn().
Member Function Documentation
bool proj_info::advance () [inline]
Puts the name and angle from the current element into the structure's members and advances icur.
Returns
false if the last element was parsed, true otherwise.
Definition at line 183 of file ts.cpp.
References angle, icur, list, and name.
Referenced by main().
Member Data Documentation
float proj_info::angle
Last acquisition angle in the file.
Definition at line 135 of file ts.cpp.
Referenced by advance(), main(), and proj_info().
unsigned proj_info::icur
Current element.
Definition at line 136 of file ts.cpp.
Referenced by advance(), and proj_info().
vector< pair<float,string> > proj_info::list
List containing the angle-file pairs.
Definition at line 133 of file ts.cpp.
Referenced by advance(), main(), and proj_info().
string proj_info::name
Last file name met in the file.
Definition at line 134 of file ts.cpp.
Referenced by advance(), main(), and proj_info().
The documentation for this struct was generated from the following file:
/home/antonmx/work/projects/ctascmake/src/executables/ts.cpp