/home/antonmx/work/projects/ctascmake/src/executables/ts.cpp File Reference
Tomosynthesis reconstruction.
#include `../common/common.h`
#include `../common/kernel.h`
#include `../common/poptmx.h`
Classes
struct clargs
Variables affected by the the command line arguments.
struct proj_info
Parses input data file.
Functions
int main (int argc, char *argv[])
Main function for 'ts'.
Variables
const string TSconfigDesc = `The path to the file is relative to the path of the data file.`
Description of the TS input configuration file.
Detailed Description
Tomosynthesis reconstruction.
Author
antonmx <antonmx@gmail.com>
Date
Mon Jul 21 10:09:31 2008
Main file for the program which reads the input sinogram from image, performs CT reconstruction of it and stores the result in other image file
Definition in file ts.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function for 'ts'.
Parameters
argc Number of the command line arguments.
argv Array of the command line arguments.
Returns
Exit status. 0 if OK, nonzero otherwise.
Definition at line 197 of file ts.cpp.
References proj_info::advance(), proj_info::angle, clargs::beverbose, clargs::center, clargs::command, clargs::contrast, clargs::data_name, exit_on_error(), ImageSizes(), proj_info::list, proj_info::name, clargs::plane, ReadImage(), clargs::result_name, SaveImage(), clargs::SaveInt, toString(), and ts_add().
Variable Documentation
const string TSconfigDesc = `The path to the file is relative to the path of the data file.`
Description of the TS input configuration file.
Definition at line 57 of file ts.cpp.