.\"{{{}}}
.\"{{{  Title
.TH CTAS 1 "" "" "User Commands"
.\"}}}
.\"{{{  Name
.SH NAME
ctas \- Interface to all commands in the \fBctas\fP package.
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.B ctas
.RI [OPTIONS]
.RI [COMMAND
.RI [COMMAND\ SPECIFIC\ .\|.\|.] ]
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
.B ctas
is the command line interface (CLI) to all commands provided by the \fBctas\fP package. Any arguments or options passed after \fICOMMAND\fP are passed directly to the command and parsed by it.
.\"}}}
.\"{{{  Options
.SH OPTIONS
.TP
.BR \-h ", " \-\^\-help
Prints help message.
.TP
.BR \-? ", " \-\^\-usage
Prints brief usage message.
.TP
.BR \-l ", " \-\^\-list
Lists all existing commands.
.\"}}}
.br
.SH SEE ALSO:
.br
ctas-bg(1), ctas-ct(1), ctas-ct-abs(1), ctas-ct-dei(1), ctas-dei(1), ctas-f2i(1), ctas-rc2fd(1), ctas-sino(1), ctas-sino-abs(1), ctas-sino-dei(1), ctas-ts(1)
.RE

